### ISSUE TITLE
Status update if/when a Windows 11 version is available?

### ISSUE THREAD

**Issue by YesTrustMe** [Open-Shell/Open-Shell-Menu#1008]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Snaid1** [comment]
+1 

Is your feature request related to a problem? Please describe.
Open Shell does not work properly in Windows 11. clicking the start button shows the win11 menu instead of OpenShell. 

Describe the solution you'd like
Open Shell should work on Windows 11 like it does on other Windows Operating Systems.

Describe alternatives you've considered
Any alternative would be to use the native win11 start menu or a different start menu replacement, I also like using the Windows XP style start menu which is not available in any other start menu replacement I have tried.

Additional context
Open Shell is awesome but needs win11 support if it's to survive with how much Microsoft is pushing for people to upgrade.

**Comment by bloggingninja** [comment]
+1 Also looking for this please!

**Comment by komawoyo** [comment]
https://github.com/Open-Shell/Open-Shell-Menu/discussions/745
