### ISSUE TITLE
Hibernate option missing from shutdown menu on latest version

### ISSUE THREAD

**Issue by vl3214** [Open-Shell/Open-Shell-Menu#1009]

**Comment by Moonsilence** [comment]
Confirming the issue. Hibernate has been in the menu for the past years, then suddenly disappeared. I'd much appreciate a fix, as I do need Hibernate often.

**Comment by blackcrack** [comment]
hypernate is not really need, if you need it, there exist different tools and also in the WinNT by self,  
[if you use -h by shutdown.exe](https://superuser.com/questions/259791/how-can-i-use-the-shutdown-command-to-hibernate-the-computer-in-x-hours)  therewith can you also make a Button ad the desktop, if you klick the right mouse key ..  
so it's not need to be in the startmenu, unless you make a patch by yourself for the code,   
because, we have to less programmer and we need programmer for make it more compatible for Win11..   
[there gives different solutions](https://www.google.com/search?q=shutdown+hypernate)

best

**Comment by Moonsilence** [comment]
OK, thanks for the rationale why it was removed from OpenShell: Because you believe people don't need Hibernate anymore.

**Comment by blackcrack** [comment]
"i believe.." \* *__beep__** wrong, i programming not on OpenShell, here be to less programmers, so try to become more programmers here..  
I have draw up you an possible..

**Comment by strawbeard** [comment]
> Confirming the issue. Hibernate has been in the menu for the past years, then suddenly disappeared. I'd much appreciate a fix, as I do need Hibernate often.

Is this specific for Win 11 or, does this also apply to Win 10 - then I would keep release 4.1.160.

**Comment by Moonsilence** [comment]
I use Win 10

**Comment by blackcrack** [comment]
@strawbeard the step to 4.4.170 have bugfixed and make more better, there be no removed functionality ..
checkout the changelog at the Release : https://github.com/Open-Shell/Open-Shell-Menu/releases
who can read, is clear in profit !  
Moonsilence said neither wich Windowsversion he use or Version of OpenShell he use ...
the same with the first post ! @Ibuprophen should close this , this tread is confused !
best :)

**Comment by Moonsilence** [comment]
To specify my Windows version:
10.0.19044.1826 (german)
To specify my OpenShell version:
4.4.170

To elaborate on the Problem: Hibernate is missing from the shutdown menu. It was available in ClassicShell and OpenShell for many years, then suddenly disappeared. I do not remember the version when it dissapeared.

In the options, 'hibernate' is still mentioned in the tooltip for the list of words that can be entered comma-seperated to control which items apprear in the shutdown menu. However, the tooltip also says that if this list is left empty, ALL items will appear. My list is left empty (default) but Hibernate does NOT appear in the menu. I tried explicitly entering 'hibernate' into the list, which results in an EMPTY shutdown menu. The list of radio button choices for "Shutdown command" still mentions Hibernate, but selecting this results in showing "Shutdown" on the button instead.

I would kindly ask to investigate this issue and not close it. Thank you!
Perhaps it is an issue specific to Windows in German language. I have no way of comparing with Windows in English.

Your suggestions to create some desktop shortcut for a hibernate command is not an alternative. I previously used Hibernate multiple times a day for the past years, and prefer to do so over Sleep, especially considering rapidly rising energy costs.

**Comment by blackcrack** [comment]
Ich hab hier Win7 am rennen.. hier ist das "Energie sparen" (hibernate) angezeigt.
Alter, dann nimm Virtualbox und probier's aus, anstatt dauernd zu fordern, ich bin nun mehr 25 Jahre im Netz bei,
aber das die Leute einfach nur fordern, obwohl sie nichts dazu tun.. iss auch nich die feine, wir brauchen hier Programmierer oder Leute wo Patches schreiben.. Oder hast Du irgend was zu OpenShell beigetragen.. wenigstens an Wissen.. selbst bei deinen ersten Posts hast Du nicht mal dran gedacht, das Du irgend welche Infos gibst. Nur forderst..
Mach dir ein Link oder Du hast nichts.. iss mir juck.. solang OpenShell nicht active weiter entwickelt wird, wird Win10/Win11 nicht wirklich sauber unterstützt.. Da kannst Du rum jammern wie Du willst.. schau das Programmierer her kommen.. das nützt mehr..

so, because this, @Ibuprophen , close please..  now...

**Comment by Moonsilence** [comment]
Sleep = Energie sparen
Hibernate = Ruhezustand

**Comment by hyyou** [comment]
Do I miss something?  Is it really completed?

There is still no hibernate option in the current version (4.4.191).

**Comment by andrewharn** [comment]
This has definitely not been fixed. What is exactly going on? I really don't get it.

How is this thread confusing? The Hibernate function is missing in the Shut Down option. How simpler can this be?

The Hibernate function is an extremely useful feature that many users, including me, use a lot especially for work. It does not matter if you think it's "unnecessary", it's essential to many people and I doubt adding an extra option to a menu is THAT hard of a task (I'm a coder and I can grasp the difficulties of certain actions in the grand schemes, even if I don't know exactly 1 to 1 the code you guys are handling). Having this issue just being put under the rug like this, with a "it's useless just do it via a command prompt bro" is lazy, an ugly replacement, and defeats the purpose of having Open Shell, not to mention it isn't user friendly to everyone.

You even complained (in German, which completely alienates who doesn't know the language and wants to contribute to this) that users were "demanding" the thing, and we should instead "hire" devs for you to help. First of all, no one here did that. We are mere fans reporting an issue, and it's not our business to search devs for you guys to help; that's your job.

This was handled incredibly poorly. I hope the devs will reason with this in a better and clearer way and this will be opened again, because it's just right to do so.
