### ISSUE TITLE
Clicking "reboot" does nothing, works with Win10's start menu.

### ISSUE THREAD

**Issue by Catfriend1** [Open-Shell/Open-Shell-Menu#1015]
**Describe the bug**

**To Reproduce**
1. Open start menu
2. Click on the arrow beside "Shutdown"
3. Click"Reboot"
4. Nothing happens.

**Expected behavior**
Windows should reboot.

**Version:**
 - Open-Shell: 4.4.169
 - OS: Windows 10 1903

**Additional context**
- Running Win10-Pro-1903 in a VirtualBox VM, VBOX 6.1.32r149290 , guest additions up2date an running.
- If I exit OpenShell and click the "official" start menu of Windows, then the "shutdown icon", a menu opens also offering "Shutdown", "Reboot". If I choose "Reboot", the system reboots fine. So this has to do with OpenShell.

**Comment by Nachtwind72** [comment]
Same problem here with OpenShell on a Windows Server 2022 - Reboot and Shutdown dont work, same when i use "shutdown -r" or "shutdown -s" in a normal cmd-window. If i use the commands in a cmd-window as administrator, it works.
Maybe there is a problem with permissions? Behaviour of OpenShell looks perfectly as normal cmd-window.
The Problem is repeatable on a fresh installed Server (VM) with all installed Updates.

**Comment by ge0rdi** [comment]
I was able to replicate this behavior by removing `Shut down the system` privilege from `Users` group in:
`Local Security Policy` -> `Local Policies` -> `User Rights Assignment`

After that `explorer.exe` or any other process running as normal user (or non-elevated admin) doesn't have `SeShutdownPrivilege` and thus shutdown/reboot is denied.

It seems that reboot/shutdown issued from standard start menu somehow circumvents this (most likely using some silent elevation in case of admin user).
Will have to investigate how does it work exactly.

> Joining a domain seems the problem.

That's because your domain most likely forces policy to deny shutdown for standard users.

**Comment by ge0rdi** [comment]
I have found out that if limited admin doesn't have shutdown rights, Windows is doing silent elevation and initiates shutdown using this command:
`%systemroot%\system32\SystemSettingsAdminFlows.exe Shutdown <flags> <reason>`

Provided `flags` and `reason` parameters are decimal numbers that go directly to `InitiateShutdownW` API call.
All the shutdown handling is implemented inside `shutdownux.dll`.

I'd like to use this in `Open-Shell` as well.

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

**Comment by Catfriend1** [comment]
I can confirm the problem is fixed. Good work.
