### ISSUE TITLE
What happened to release 4.4.160??

### ISSUE THREAD

**Issue by foxxcomm** [Open-Shell/Open-Shell-Menu#1017]
Since this afternoon release 4.4.152 is current and 4.4.160 has disappeared. Is GitHub losing releases again?

**Comment by Ibuprophen** [comment]
Are you referring to this one? 

https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.160


~Ibuprophen

**Comment by foxxcomm** [comment]
Yes - however if we open the main page on GitHub since this afternoon, under releases on the right hand side it shows 4.4.152 as the current and latest release:

https://github.com/Open-Shell/Open-Shell-Menu

**Comment by Ibuprophen** [comment]
Ahh... I'm not sure why the version isn't reflecting the current official version released. 

I was able to get the current version to display in the list of Releases (instead of having to go to the tagged list to see it). 

I think this might be a Github specific glitch, but I can't really point fingers since I'm not sure of what's really the issue. 

Maybe @XenHat, @ge0rdi, @coddec might be able to shed some light on this. 👍 

~Ibuprophen

**Comment by ge0rdi** [comment]
I can see 4.0.160 there. No sign of any issue:
![image](https://user-images.githubusercontent.com/2453094/167702245-36aaa11b-2fe3-4645-8b7d-e3dd0c309260.png)

**Comment by Ibuprophen** [comment]
@ge0rdi, I do apologize for this... 

The following is now correct, but it wasn't when I had last posted. 

![Open Shell Example 1](https://user-images.githubusercontent.com/18060271/167730698-6a5dbb14-4024-496e-a6cc-1a15f1d02071.jpg)

Since it all looks good to go @foxxcomm, I will consider this as resolved. 

Thank you all for your time, patience and understanding with this. 👍 

~Ibuprophen
