### ISSUE TITLE
Classic Explorer no longer working on Windows 8.1 [SOLVED]

### ISSUE THREAD

**Issue by alexonski** [Open-Shell/Open-Shell-Menu#1028]
Classic Explorer is (was - see solution below) no longer working for me on Windows 8.1.  I can open and make changes in the "Settings for Classic Explorer 4.4.160" from the start menu, but the toolbar no longer appears in the windows file browser and none of the settings (e.g. disable breadcrumbs) seem to have any effect.  I have tried: restarting, repairing, uninstalling and reinstalling Open Shell, all to no avail.

I first noticed the issue after installation of some windows updates including but not limited to:
2022-05 Servicing Stack Update for Windows 8.1 for x64-based Systems (KB5014025)
2022-05 Security Monthly Quality Rollup for Windows 8.1 for x64-based Systems (KB5014011)
2022-05 Security and Quality Rollup for .NET Framework 3.5, 4.62, 4.7, 4.7.1, 4.7.2, 4.8 for Windows 8.1 for x64 (KB5013872)

Version:
Open-Shell: 4.4.160
OS: Windows 8.1 Pro with Media Center

SOLUTION thanks to GGRFH, below:
The Classic Explorer Bar Internet Explorer add-on has to be enabled in Internet Options in the Control Panel > Internet Options > Programs > Manage Add-ons.  Right click on "Classic Explorer Bar" and select "Enable".

You then need to log off/on Windows (no reboot needed), and Classic Explorer should now be working again.

Before (not working):
![before](https://user-images.githubusercontent.com/67078639/178055358-17dd20aa-7533-4374-bf77-c3599ae34c48.png)
After (working)
![after](https://user-images.githubusercontent.com/67078639/178055500-caa772be-78b5-48f1-bee1-6d0601d1ee54.png)

**Comment by namiltd** [comment]
Check if it will be the same for the new system user. It will be known whether it is a matter of user or system settings.

**Comment by alexonski** [comment]
Indeed the problem is specific to only one user account.  A reset of Classic Explorer settings also does nothing to resolve this for that account.  Any other suggestions would be appreciated.

**Comment by namiltd** [comment]
Try deleting app data:
```
c:\Users\_USERNAME_\Appdata\Local\ClassicShell
c:\Users\_USERNAME_\Appdata\Local\OpenShell
c:\Users\_USERNAME_\Appdata\Roaming\ClassicShell
c:\Users\_USERNAME_\Appdata\Roaming\OpenShell
```
Log out and do this on another user, or close OpenShell application first.

**Comment by alexonski** [comment]
Thanks but deleting the app data folders after closing OpenShell did not resolve the problem.

**Comment by namiltd** [comment]
Check Application Logs for errors (click "Control Panel" > "System and Security" > "Administrative Tools", and then double-click "Event Viewer" .

**Comment by alexonski** [comment]
@namiltd: Thanks for your suggestions.  There were several errors in the Event Viewer, but I wasn't able to find any that seemed to correlate.

Looks like the next step is to create a new replacement profile in Windows...

**Comment by atesin** [comment]
hi...  i have the same situation

i opened the event viewer...  which category should we look (there are so many)...  which should i search? .. some string or something?

**Comment by GGRFH** [comment]
> Classic Explorer is no longer working for me on Windows 8.1. I can open and make changes in the "Settings for Classic Explorer 4.4.160" from the start menu, but the toolbar no longer appears in the windows file browser and none of the settings (e.g. disable breadcrumbs) seem to have any effect. I have tried: restarting, repairing, uninstalling and reinstalling Open Shell, all to no avail.

I'm pretty sure I had the same problem with 8.1 and it had to do with the BHO Class extension Add-ons which has to be enabled in **Internet Option** in the Control Panel > Internet Option > Programs > Manage Add-ons

![BHO Class](https://user-images.githubusercontent.com/37418402/177987179-e99bb064-4858-406d-82e2-1b30f4cf7692.png)

**Comment by blackcrack** [comment]
already tried last Version ?
[ 4.4.170 --==>> Last Release ](https://github.com/Open-Shell/Open-Shell-Menu/releases/latest)

**Comment by blackcrack** [comment]
this i whanna hear :  
>At Work :
>Open Shell is working perfectly.
>Classic Explorer IS NOT WORKING : version 4.4.170

now can you bring the code, because we have no active programmer here..
if anyone bring code too, it's nice too :))

by the way, if you have in the work/Store or Facility a programmer, 
hey, kick him on for a couples code lines ;) hihi ..
also a possible for get an couples lines of code for our OpenShell ;)

best

**Comment by Ibuprophen** [comment]
Did you try installing the software as an Administrator? 

Right click the exe (software installer) and select the Run/Install as an Administrator option. 

~Ibuprophen

**Comment by alexonski** [comment]
> > Classic Explorer is no longer working for me on Windows 8.1. I can open and make changes in the "Settings for Classic Explorer 4.4.160" from the start menu, but the toolbar no longer appears in the windows file browser and none of the settings (e.g. disable breadcrumbs) seem to have any effect. I have tried: restarting, repairing, uninstalling and reinstalling Open Shell, all to no avail.
> 
> I'm pretty sure I had the same problem with 8.1 and it had to do with the BHO Class extension Add-ons which has to be enabled in **Internet Option** in the Control Panel > Internet Option > Programs > Manage Add-ons
> 
> ![BHO Class](https://user-images.githubusercontent.com/37418402/177987179-e99bb064-4858-406d-82e2-1b30f4cf7692.png)

Thanks, enabling the "Classic Explorer Bar' in Internet Options -> Programs -> Manage Add-ons brought Classic Explorer back into operation for me on Windows 8.1!

**Comment by 4C3T** [comment]
Does this apply for Windows Server 19 as well?
I did manage to find the settings as [GGRFH](https://github.com/GGRFH) showed an image of, but since I'm running Swedish, I had to guess my way there a bit, but I got it, and enabled it.
I know I should've tried rebooting first, but I'm running a server and I can't reboot just yet (For a few reasons, one: I removed Avira (don't ask!) and haven't rebooted since. Two I'm running a server that's currently doing a bunch of stuff. Three, usually Open-Shell applies setting directly.)

And, since Windows 19 is completely mongo in many senses, I wouldn't be surprised if I absolutely had to.

**Comment by alexonski** [comment]
> I know I should've tried rebooting first, but I'm running a server and I can't reboot just yet

At least on Windows 8.1, all that is needed is a log off/on after re-enabling the "Classic Explorer Bar" in Internet Options.

**Comment by 4C3T** [comment]
Ok. Sometimes I amaze myself. I created a new account and did the same changes there, logged in & out a couple of times, but it doesn't seem to work.

It really does bother me that MS has FUBAR:ed up the Server versions by mimicking the desktop versions, even removed/added fluff (Like, on a server - Which admin wants to have to enable view hidden files/folders, show encrypted files in different colors etc???) or all the graphics crap that slows everything down (no to mention huge building sized icons) and everything everywhere.
At least (In desktop versions) many settings are stored online with Windows ID & that.

And, what I was going to type, was that many settings, tweaks & trix that work on desktop versions doesn't work on the server versions. No errors, no clues (most of the time), just nothing. Either you find something online (sift through forums or MS Q&A (or get the F out of there), or you give up and either reinstall or install something else).

**Comment by Ibuprophen** [comment]
@4C3T, the information here should still apply to both these Windows Platforms. 

It's been quite some time since I've used a Server Platform and your mention of it really threw me back in memory... LOL! 

The only Windows OS (I can think of) that would require additional work to allow the Shell Software to work on would be the Windows Virtual platform. 

Thanks for mentioning this for clarification purposes. 

~Ibuprophen

**Comment by atesin** [comment]
sorry to bother....  but this issue was closed and tagged with [solved] ...  and i still have the problem (with classic **windows explorer**, not classic internet explorer)

what must i do to resolve the issue?

**Comment by atesin** [comment]
hry i think this issue is not resolved yet...  the title says "**Classic Explorer** no longer working..."
as i understand, "classic explorer" refers to classic "windows explorer" (file manager, the yellow folder app), otherwise would be "classic **internet** explorer"

![image](https://user-images.githubusercontent.com/8086106/183510920-f0f19fe6-2489-4cd9-9575-df386da6dce7.png)

![image](https://user-images.githubusercontent.com/8086106/183511007-7bce2617-523a-425b-8a10-4d081e0a4a6a.png)
