### ISSUE TITLE
Crash when opening Recent Documents item at menu top

### ISSUE THREAD

**Issue by qretornaz-adapei42** [Open-Shell/Open-Shell-Menu#1032]
Hello,
I’m experiencing crashes that I can reproduce everytime I’m putting my mouse over Recent Documents item that is at the top of the menu for some seconds before explorer.exe crashes.
The item on the menu is the following:
![Capture](https://user-images.githubusercontent.com/68447452/171273171-8dd8288b-9d65-41e7-ac28-dd089a9748c1.PNG)
On this machine, Documents directory is redirected to a file server.
I’ve attached here a crash bump.
[explorer.exe_220531_214304.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/8808969/explorer.exe_220531_214304.zip)

**Comment by ge0rdi** [comment]
Are you still able to reproduce?
If so, then please try to provide full dump (instead of mini-dump).

`Open-Shell` is trying to enumerate items from Recent documents shell object and call to `IEnumIDList::Next` causes like endless recursion in some system components that will end up eating whole stack and crashing Explorer process.

This is weird, because the call we are doing is standard one and works well elsewhere.
Could it be some issue on your machine?
Maybe try to upgrade to latest Win10 22H2.
