### ISSUE TITLE
Cannot check for updates with Open-Shell Update App..

### ISSUE THREAD

**Issue by michaelleepow90** [Open-Shell/Open-Shell-Menu#110]
Is there a way to fix this? I opened Open-Shell Update to check for updates but got the following error;

> **Failed to check for new version**

 Even though my modem is online.. 

Oh, also at the bottom left corner I noticed the website www.classicshell.net by the way..

**Comment by ibuprophen1** [comment]
I had thought that this was one of the items on the "to-do" list regarding the invalid URL location with checking for updates. 

I do know that it's a a very long process in correcting/clarifying the SLEW of Classic Shell URL's and such throughout the software while maintaining credits for the original developer as well. 


~Ibuprophen

**Comment by coddec** [comment]
@XenHat @ge0rdi 
Is it possible if we use a text file here https://open-shell.github.io/Open-Shell-Menu/ or use raw url from our repo with latest version number manually entered every time we published new version, then the update app check and compare the software version with the urls mentioned above?

Will it work?
Which way is the easiest? So that we can save some time while still make it work :D

**Comment by LinuxOnTheDesktop** [comment]
For what it is worth: I have the same problem, even with my firewall disabled.

**Comment by coddec** [comment]
@LinuxOnTheDesktop I think it's not fixed yet, the link for the software to check the update is not changed yet.

**Comment by an0nimo** [comment]
The same problem here (windows 10). 🤕

**Comment by ibuprophen1** [comment]
I had just recently looked into this. I did locate a few items that require updating but, I'm still touching base with some other items as well. 

I'm just hoping for that "HA-HA!" moment... LOL! :-) 


~Ibuprophen

**Comment by LinuxOnTheDesktop** [comment]
Right.

(You might get an '_ah_-ha' moment. I fear that asking for '_ha_ ha' in software development might be asking a bit much!)

**Comment by ge0rdi** [comment]
Update component was already removed from installation package.
It may get back once we make it working.

**Comment by ge0rdi** [comment]
I'd like to let you know that latest nightly build (4.4.156) contain support for auto updates.
It is also possible to check for nightly updates.

**Comment by manbazza** [comment]
I've just updated to 4.4.160 (from 4.4.142). I see that OpenShell now trying to auto update periodically.  Is there some way to disable the auto updates (I've had a good look around and I cannot see anything obvious).

Ta!

**Comment by ge0rdi** [comment]
- Start `Open-Shell Update`
- Uncheck `Automatically check for new versions` check-box
- Press `OK`

**Comment by manbazza** [comment]
geordi, 

Thanks for the pointer. 

I surmised that Open Shell was trying to update as Explorer.exe was attempting to access Internet  after i updated to 4.4.160, but blocked by my FW.

I didn't have the updater installed. Must say seems somewhat perverse to have to install the updater in order to disable updating.  Maybe auto update should be off by default rather than on (as it seems to be).

Anyways, my immediate issue fixed now. Thanks again.

**Comment by Moopere** [comment]
> * Start `Open-Shell Update`
> * Uncheck `Automatically check for new versions` check-box
> * Press `OK`

Thanks for this.  Suddenly got pop-ups everywhere and it wasn't obvious how to turn them off.

Is there any chance we could check in HKLM for the same setting and by doing so make it machine wide?

**Comment by ge0rdi** [comment]
> Is there any chance we could check in HKLM for the same setting and by doing so make it machine wide?

Creating DWORD item `Update` with value 0 in `HKLM\Software\OpenShell\OpenShell` should do the trick.

**Comment by Moopere** [comment]
@ge0rdi - thats seems to be it - thanks.  Greys out the ability for users to change the setting in 'open-shell Update'  (update.exe) which is nice.
