### ISSUE TITLE
No obvious way to uninstall

### ISSUE THREAD

**Issue by kolbaba** [Open-Shell/Open-Shell-Menu#1124]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I had to use Revo uninstaller to remove this from my machine

**Describe the solution you'd like**
An option to uninstall. I didn't see anything in "Add/Remove Programs" either.

**Comment by blackcrack** [comment]
@ge0rdi

**Comment by biznizz** [comment]
What OS are you using?

Because in Win10, Open Shell is very clearly shown in Programs and Features and is very easy to uninstall.

**Comment by ge0rdi** [comment]
`Open-Shell` is normally present among installed Apps & Features:
![image](https://user-images.githubusercontent.com/2453094/189520594-d6a63cef-a096-4061-8ae2-2cdfd993e22c.png)

Make sure you are using latest official release.

Feel free to reopen if you are able to replicate the behavior.
But please, provide also version of Windows and Open-Shell.

**Comment by typosudo** [comment]
hj

**Comment by 13x0** [comment]
I opened Task Manager (ctrl + shift + esc) and into "Apps > Installed Apps", scrolled down to OpenShell and uninstalled. I manually stopped the task for explorer.exe, then selected whatever other option there was instead of the option that would reboot my pc. uninstalled it then i manually re opened the explorer.exe by clicking "Run new task" at the top right of Task Manager. You may also do this by doing ctrl + r, which will open the run menu. In the run menu, type "explorer.exe", and then you are all good to go. Thats everything I did, and so far no issues for me.
