### ISSUE TITLE
Installs updates on reboot regardless of general behavior setting

### ISSUE THREAD

**Issue by Lukas2438** [Open-Shell/Open-Shell-Menu#1250]
**Describe the bug**
When rebooting or shutting down your computer using the Open-Shell menu, it will still install updates.
I checked the corresponding setting in the General Behavior section, but the "Check for Windows updates on shutdown" is already unticked for me.
Though when right-click on the Start Menu button and choosing shutdown or reboot (without the "update and ...") from the context menu, Windows do not update at this point. Tried this a few times now, with feature updates and .NET Framework too.

**To Reproduce**
1. Wait for Windows finding/downloading new updates, that require a reboot of the system.
2. Verify the "Check for Windows updates on shutdown" in General Behavior is ticked.
3. When prompting for computer restart, click on reboot in the Open-Shell menu.
4. Windows will reboot but still install pending updates as you can see on the screen.

**Expected behavior**
Open-Shell should pay attention to that menu setting. Maybe some algorithms changed with a previous windows update.

**Version:**
 - Open-Shell: 4.4.170 stable
 - OS: Windows 10 Pro 22H2

**Comment by ge0rdi** [comment]
Standard `Restart` action is supposed to just reboot machine without applying updates.

`Check for Windows updates on shutdown` option shouldn't affect behavior of `Restart` action.
It only checks if there are updates prepared (not 100% sure it works properly in recent Windows versions) and then adds `Update and restart` and `Update and shutdown` options to shutdown button.
So that user can choose what action to do.

Can you replicate the issue somehow without waiting for some Windows update (so that it is easier to debug)?

Do you have `Update and restart` option in `Open-Shell` shutdown button in such state?
![image](https://user-images.githubusercontent.com/2453094/207931301-7b50a4d0-b907-44eb-9be5-e51b0542ba2a.png)

Does running `shutdown /r /t 0` from command line restart machine without applying updates?

**Comment by Lukas2438** [comment]
Today I had no advanced menu like in your picture, only _switch user_, _log off_, _lock_ and _restart_ (shutdown too, of course).
But there were updates prepared and waited for a restart to complete. I think this menu only expand when high priority updates are in queue.
I will do extended testing by uninstalling updates and redownload them, hoping for another restart-to-complete situation.

**Comment by Lukas2438** [comment]
Alright, tested three different ways to avoid the update completion:
1. Open-Shell: besides there's no detailed shutdown menu it will install the update in queue
2. Start context menu (Win+X): won't install update when clicking the appropriate action
3. `shutdown /r /t 0`: installs the update just like using Open-Shell menu

Tested update: **KB5021089 (.NET Framework)**


![OpenShell-RestartUpdateIssue](https://user-images.githubusercontent.com/26190230/207946383-7f552471-38dc-42ca-9c43-2b6928808cc2.jpg)
![OpenShell-RestartUpdateIssue2](https://user-images.githubusercontent.com/26190230/207946401-ba9fd7b9-f0b0-4a8d-95a2-11190fb531ee.jpg)

**Comment by ge0rdi** [comment]
Thanks for info.

It seems that standard Windows API (that `Open-Shell` and `shutdown` uses) just always applies updates.
So we need to figure out how to do shutdown/restart without applying them.

**Comment by ge0rdi** [comment]
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.
