### ISSUE TITLE
Helllpppp!

### ISSUE THREAD

**Issue by PDL2CGamejolt** [Open-Shell/Open-Shell-Menu#1289]
### Describe the bug

I CANNOT UNINSTALL IT!

### Area of issue

Installation/Other

### To reproduce

Simple, TRY TO UNINSTALL IT.

### Expected behavior

I expected it to uninstall, obviously,

### Open-Shell version

???

### Windows version

Windows 11 RTM(?)

**Comment by ge0rdi** [comment]
This is so badly written report that I will just close it right away.
Feel free to create new issue and provide information in clear way.

> Helllpppp!

Such issue title doesn't make any sense. If you cannot uninstall then at least write `Cannot uninnstall`.

> I CANNOT UNINSTALL IT!

Ok, nice. But quite useless (not mentioning the rudeness of the message).
You should rather describe what happens when you try to uninstall. Will it display some error messages? Provide some screenshots for clarify, etc.

> ???

It is important to know what `Open-Shell` you are using.
You can easily find it in Windows `Apps and Features` window. Or running `Open-Shell Menu Settings` from start menu.

Anyways, you can start by installing latest [available version](https://github.com/Open-Shell/Open-Shell-Menu/releases).
And eventually then uninstall it.

> Windows 11 RTM(?)

Again, this is vital information. I guess it shouldn't be a problem to provide proper Windows version (without any question marks).

Last but not least, for discussing _vague_ issues such as this there are [discussions](https://github.com/Open-Shell/Open-Shell-Menu/discussions/categories/q-a) where you can ask for help with your issue (using decent polite tone).
