### ISSUE TITLE
Error in assembly of the group policy template - OpenShellStartMenu.adml

### ISSUE THREAD

**Issue by vodek3** [Open-Shell/Open-Shell-Menu#1318]
### Describe the bug

After building Open-Shell and building the group policy templates, all files were built correctly, except for one - OpenShellStartMenu.adml

The hint "Warning: the search service is disabled" disappears somewhere...
In the source file: `Src\StartMenu\StartMenuDLL\StartMenuDLL.rc` this is line 935:
`        IDS_SEARCH_FILES_TIP2 "When this is checked..."`
![image](https://user-images.githubusercontent.com/25941601/215748082-5232639d-bb5e-4443-a075-f64d2c164291.png)

[OpenShellStartMenu.adml.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/10546014/OpenShellStartMenu.adml.zip)

1. Template from build 4.4.189
2. Template from my build

### Area of issue

Installation/Other

### To reproduce

I compiled several times

### Open-Shell version

4.4.190

### Windows version

Windows 10 22H2 19045.2486

**Comment by ge0rdi** [comment]
ADMX/ADML files are generated during build using settings compiled in `Open-Shell` binaries.

Tooltip for `SearchFiles` setting depends on state of `WSearch` service:
https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/StartMenu/StartMenuDLL/SettingsUI.cpp#L5009

Thus the description string that goes to ADML will depend on whether build machine has search service running or not.

It seems that AppVeyor workers don't have such service running (so there is this `Warning: the search service is disabled` part in official ADML files) and your machine has the service running.
That's why there is the difference.

I admit it is not ideal (though rather cosmetic issue).
I'll think what we can do with it.

**Comment by vodek3** [comment]
It's does not work! Do you know why?
Because you forgot reason... 
This one:
`\nWarning: the search service is disabled`
see pic. 1

Correct string is
`SearchFiles.tipOverride = When this is checked, the search results will include files, emails and other items from indexed locations\nWarning: the search service is disabled`

**Comment by ge0rdi** [comment]
Nope.
There is no point to display `Warning: the search service is disabled` in group policy setting.
That string is simply a hint for the user when editing actual `Open-Shell` settings that Windows Search service is disabled.

**Comment by vodek3** [comment]
You are extremely inattentive... In this case, I draw your attention to this fact for the third time minimum. This is a fact.
I even attached pictures on purpose so that it is very clear what I'm talking about.
Yes, this is a warning. =D And it is not displayed. Yes.
And it starts to be displayed after you carefully compare pictures 1 and 2 and will write `\nWarning: the search service is disabled` at the end. Just add it. Everything will be alright. ;-)

Look, why are you arguing with the obvious? This is stupid. It is a fact.

**Comment by ge0rdi** [comment]
I understand what is in the pictures and what you have reported.

But as I wrote it was simply a bug in `Open-Shell`.
ADML file contained `Warning: the search service is disabled` string by mistake.
There is simply no point of displaying such information when editing group policy. Group policy editor doesn't know/care if some service is running or not. So showing information that is simply false in 50% of cases doesn't make any sense.

I thank you for pointing out this bug.

As everything was explained, I'm locking this issue.
