### ISSUE TITLE
Right-click on OpenShell icon or all program items don't show context menu

### ISSUE THREAD

**Issue by pkirkaas** [Open-Shell/Open-Shell-Menu#1331]
### Describe the bug

After "upgrading" to Windows 11 Pro 22H2, right-click on the Open Shell Icon doesn't give a context menu.

Left-click does produce the normal expected menu items, programs, apps, etc - but right-clicking on any of the items also fails to show a context-menu.

This was not an issue before the upgrade to 22H2

### Area of issue

Start menu

### To reproduce

Right click on Open Shell menu start button

### Expected behavior

Get the previous right-click context menus

### Open-Shell version

4.4.189

### Windows version

Windows 11 Pro 22H2,

### Additional context

Also with latest stable release, 4.4.170

I also use "ExplorerPatcher" (https://github.com/valinet/ExplorerPatcher) - which gives old taskbar-like behavior, and again has been flawless (just like Open Shell Menu) UNTIL "upgrade" to Windows 11 Pro 22H2.

**Comment by ge0rdi** [comment]
To clarify, you mean that this context menu doesn't show after right-click on Start button, right?
![image](https://user-images.githubusercontent.com/2453094/218652195-59c642d1-fbce-494d-a79c-5121be1121c9.png)

**Comment by pkirkaas** [comment]
Hi Geordi(?) - Yes, exactly. Left-clicking works fine to open the start programs, I can launch everything fine - but I used to be able to right-click on a program group & open it in explorer, copy the link & paste it elsewhere, etc. No right click works for me anywhere in Open Shell for me.

And to be clear, it's not a "bug" in Open Shell, which I have been delighted with for years. It started when I first "upgraded"  Windows 11 to 22H2, six months ago. I downgraded Windows 11 and the problem went away. But MS kept nagging about the importance of 22H2, and I hoped in 6 months MS had resolved that, so last week I re-upgraded to 22H2, and had the issue again.

For your context, it's not just Open Shell - I have weird menu issues with several (but no many) apps...

I use Vim/GVim as my text editor. After 22H2, the menus didn't go away - but they were collapsed and empty - both context and top menus - just a narrow grey box where the menu items should appear. I uninstalled & reinstalled vim -- not a new version, just re-installed - and now that works.

I also use SmartGit for my Git Gui. There, the menus just don't appear at all - neither context nor top level. Nothing. Re-install, nothing.  So I installed SourceTree as my Git Gui, and that works fine.

All I can imagine is that MS supports a few different ways of opening menus - and one of those ways was broken by 22H2. And not for everyone.

I totally get this is not a top priority for you, but I'm a software developer as well. I can't test everything, and I really appreciate feedback from users who catch issues I missed.

So this is just an FYI - in case you get bored some evening & looking for something to do.

Anyway, just want to express my appreciation again for keeping Open Shell alive. So many users complain about all the problems with every new version of the start menu provided by Microsoft - but with Open Shell, I've never had to think about it.

PS: As I mentioned I also use ExplorerPatcher (https://github.com/valinet/ExplorerPatcher) to fix the task bar. Are you familiar with that? Can I do the same thing with Open Shell? (I'm not familiar with all the Open Shell configuration options).

I was wondering if there might be some conflict with Open Shell & ExplorerPatcher, but it's more than that - I have W11 22H2, Open Shell & ExplorerPatcher on my entertainment computer as well, and everything plays well together there.

Those are the most annoying bugs to try to track down & fix...

Thanks,

Paul

**Comment by ge0rdi** [comment]
> For your context, it's not just Open Shell - I have weird menu issues with several (but no many) apps...

I'm afraid that there is something (maybe some misconfiguration) on your machine that causes this. Since it affects more different applications.
I'm not sure I can help with that. I haven't heard about such issues on Win11 22H2.

> I was wondering if there might be some conflict with Open Shell & ExplorerPatcher

That's the first thing I'd try to check. You can uninstall `ExplorerPatcher` and see if that will help.
Also if you have any other such customization/hacking program, you can try to remove it.

I will close this as we cannot do anything about it.
Though feel free to post here if you'll have anything new.

**Comment by PeaceByJesus** [comment]
I also use Explorer Patcher and have the same and a similar issue, meaning after "upgrading" to Windows 11 Pro 22H2, not only does a right-click on the Open Shell Start icon not provide the Open Shell settings access in the context  menu (though it provides other items that I placed there), but worse, a right click on any App or Program shortcut icon in the  Start menu only results in a brief hourglass but no menu or window. Pressing the function key while pointing to the icon does the same thing. 
![printkey318](https://user-images.githubusercontent.com/9687219/221448140-cb95bac9-d9d4-4d30-b316-5b8b6e651ec6.jpg)

I uninstalled both .Explorer Patcher as well as 7+ taskbar Tweaker (better than the default) but it and restarted explorer.exe but it did not fix it. Open Shell  and Explorer Patcher  still worth it though, thank God for those who code and offer  such!

**Comment by pkirkaas** [comment]
Totally get this is not a top priority, but since someone else reported the issue, I figured I would poke it.

I also wrote the developer of Explorer Patcher - in case he has any insights.

But like "PeaceByJesus" said - thank god for the work you do. For everyone who writes to thank you, there are thousands more  who are grateful every day but never reach out to tell you.

Thanks,

Paul

**Comment by PeaceByJesus** [comment]
Yes, we should express gratitude more in this area, not only because of operating systems but for those who work to improve Windows by "fixing" some things MS imagines are improvements, as well as providing enhancements for more efficiency,  and which Open Shell does. A vast improvement over the standard Windows Start menu. I also used WinTweaker, among others, but the 22H2 update it what changed things.  Sometimes a right click on a Start menu program  icon will not simply result in a momentary hourglass and then nothing, but it will launch a program (not a menu) located somewhere else,  

BTW, I tried the a fix described here https://www.thewindowsclub.com/disable-right-click-context-menu-in-start-menu-of-windows-10 except the Value data was 0, yet that did not restore it after restarting explorer.exe. Nor this on the Get-AppXPackage  https://gearupwindows.com/fix-right-click-not-working-in-start-menu-or-start-button-of-windows-10/, but I did not engage in the WinX replacement. Neither did the UseExperience reg key creation (better described here: https://thegeekpage.com/fix-right-click-not-working-on-start-menu-taskbar-in-windows-10/) do anything.  And User Configuration > Administrative Templates > Windows Components > File Explorer in n Group Policy Editor   is not configured, meaning it is not disabled.  And I save to Favorites most any recent Reg. key I change.

**Comment by PeaceByJesus** [comment]
To update, W/11 KB5033920  update  also  broke right click function on any programs  or apps in the Start menu. 

Open Shell   is a real blessing, thanks - a vast improvement over MS default (what were they thinking?)  but MS update is the problem. After the W/11 KB5033920  update (related to .NET Framework 3.5 and 4.8.1) under ver. 22H2 then right click on any programs  or apps in the Start menu  no longer  works to provide a menu. None work. There is just a nano-second  flash of an hourglass and nothing happens. The menu key does nothing while a app name is selected either, and  Windows key and r  no longer brings up the Run command. 

However, if I go to the default Windows Start menu  (from Open Shell) then r. click works.  And uninstalling Open Shell restores the function. 

I had this loss of  function before after a Windows update, which I think I blocked, but I will have to  uninstall this update so that Open Shell works.  I use Explorer Patcher  as well and uninstalled that  temporarily to see if that would fix this problem but it did not. 

But I thank God for you who  provided  this "essential fix" for Windows default.

**Comment by SteverB11** [comment]
While looking for this issue too, I just found out that if you hold the SHFT key while right-clicking all the Open-Shell menus return. Something about Windows right-click menus being "streamlined." It's annoying, but a workaround.

**Comment by ge0rdi** [comment]
> I just found out that if you hold the SHFT key while right-clicking all the Open-Shell menus return

Most likely you have `Right click opens Win+X menu` option enabled.
In such case right-click on start menu opens standard Windows context menu. And shift+right-click opens `Open-Shell`'s context menu.

**Comment by SteverB11** [comment]
Oh, I just reread the OP. He was only talking about the right-click on the Start button. For a while tonight, I couldn't right-click on the Start button **OR** any Desktop icons and get the Open-Shell menus. I read somewhere else to press Shift, but now that I've installed Bulk Renamer and Files2Folders, which both add stuff to the right-click menu on the desktop, the Open-Shell menus are back without pressing Shift. I'm just now switching to W11, since Microsoft seems pretty insistent about it before October. I'm on the latest version of Windows 11 24H_something_. Windows, through the years, has always been weird and that weirdness continues. Thanks, and cheers!
