### ISSUE TITLE
Open-Shell behavior on multi-user machines -- safe to install without surprising all other users?

### ISSUE THREAD

**Issue by bkidwell** [Open-Shell/Open-Shell-Menu#136]
Please help me understand this before I install it and find a mess I have to manually undo:

If I install Open-Shell-Menu on a multi-user terminal server where I have admin access, will all OTHER users suddenly have their Start Menu replaced by Open-Shell-Menu the next time they login? Or will they have to launch it from their Programs menu individually and configure its auto-start behavior?

The install wizard does not make it clear before you get to the point of "elevate privileges and install".

If there is an automatic system-wide change for all users, I can't install it. This is not MY server; I'm being asked to do work on it.

**Comment by ge0rdi** [comment]
`OpenShell` (as well as original `ClassicShell`) starts automatically for every user by default.
Individual users can then disable its auto start.

If you want to prevent this behavior, you will have to manually remove `Open-Shell Start Menu` value from `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` key after installation.

Eventually you should create the same value in `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`, so that it will start automatically for your user.

**Comment by bkidwell** [comment]
This resolves my question.

**Comment by bkidwell** [comment]
Workaround: Extract the contents of the installer and do a copy-paste install to your preferred folder. Run "StartMenu.exe", edit and save settings. By default it will now automatically start for only the user that executed it.

**Comment by ge0rdi** [comment]
@bkidwell 
Please, check this comment for ways to disable `Open-Shell` autostart:
https://github.com/Open-Shell/Open-Shell-Menu/issues/161#issuecomment-500226960

**Comment by potjeh** [comment]
Agreed, after losing a lot of patience - this seems to work.

> Workaround: Extract the contents of the installer and do a copy-paste install to your preferred folder. Run "StartMenu.exe", edit and save settings. By default it will now automatically start for only the user that executed it.

Just remember to autostart it somehow.
