### ISSUE TITLE
Feature Request: Calculate in Start Menu like Spotify

### ISSUE THREAD

**Issue by smashplay** [Open-Shell/Open-Shell-Menu#143]
"Start Menu Calculator" App isn't working on Win10 /w ClassicShell

**Comment by ibuprophen1** [comment]
Your question looks like your stating that the Classic Start Menu has a Calculator app that doesn't work but, I understand what you're describing. LMAO! 

From what I've seen, regarding Windows 10, that it "technically" has 2 Calculators. 

One is specifically an App (aka Metro App) and the other is specifically software. 

Which one are you referring to? 

Also, can you please explain some details (with one or more screenshots if necessary) exactly what you specifically select, where it's specifically located and what specifically happens when you do select it? 

Thanks! :-) 


~Ibuprophen

**Comment by ge0rdi** [comment]
> "Start Menu Calculator" App isn't working on Win10 /w ClassicShell

@smashplay Could you please explain it a bit? What app do you mean? How it doesn't work? Maybe add some screenshots to clarify.
