### ISSUE TITLE
Reproducible? classic explorer crash

### ISSUE THREAD

**Issue by f1WN356Uh51a1W6cn** [Open-Shell/Open-Shell-Menu#1523]
### Describe the bug

Doing this crashes explorer.exe for me every time

### Area of issue

Windows Explorer

### To reproduce

1. open new tab
2. close a tab
3. Win+L to lock the PC

### Open-Shell version

4.4.189

### Windows version

22621.1485

**Comment by ge0rdi** [comment]
Please, provide crash dump obtained using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash).

**Comment by f1WN356Uh51a1W6cn** [comment]
So it crashes in DLLInstall I guess?
https://1drv.ms/u/s!Aui1S7TDJRdQiKxbSe_tF_Mi-yYo0g?e=Ungea4

**Comment by f1WN356Uh51a1W6cn** [comment]
I was experimenting a little and it doesn't crash if I disable "ExplorerBHO Class" in inetcpl.cpl

**Comment by ge0rdi** [comment]
> I was experimenting a little and it doesn't crash if I disable "ExplorerBHO Class" in inetcpl.cpl

It makes sense as the crash happens in [CExplorerBHO::SubclassTreeProc](https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/ClassicExplorer/ExplorerBHO.cpp#L223).

Though I'm not really sure what's the root cause (as I'm not quite familiar with `Classic Explorer` code).
I'll have to figure out how to fix it properly.

**Comment by ge0rdi** [comment]
@f1WN356Uh51a1W6cn 
Could you please test build from #1525 PR?

**Comment by f1WN356Uh51a1W6cn** [comment]
It works!! Thank you I was getting used to random crashes. Yes using classic explorer is probably just asking for trouble but it still functions in 22H2 at least
