### ISSUE TITLE
startmenu button cannot  move to left edge of taskbar 

### ISSUE THREAD

**Issue by atsushifx** [Open-Shell/Open-Shell-Menu#1534]
### Describe the bug

I set 'Align to corner of the screen' option in Settings for Open-Shell menu, but menu button is still setted on left side of centerised icons.

### Area of issue

Taskbar

### To reproduce

1. start `Open-Shell Menu Settings'
2. move 'Start Button' tab &  select 'Custom Button'
3. set 'Align to corner of the screen' option to on
4. click 'OK' and save these options.
5. `Start Menu' button is not move.

### Expected behavior

I want to move 'startmenu' button to corer of task bars left edge.

### Open-Shell version

4.4.189

### Windows version

Windows 11 22H2

**Comment by atsushifx** [comment]
At the end  settings the stary button move to left side of centerized icons,
like a picture below
[Imgur](https://i.imgur.com/aBzZgCn.png)

I want that start button would be still the left-down corner.

**Comment by ge0rdi** [comment]
It seems you are using center-aligned taskbar.
If you want to have start button on the left edge of taskbar you need to align taskbar to the left in Windows taskbar settings.

`Open-Shell` is always following the actual position of start button.

**Comment by atsushifx** [comment]
I want task-bar are center aligned. But open-shell's start button is corner of screen (left edge of taskbar).
Is settings option 'Align to corner of the screen' meaned above?
Or that I wants must have an enhanced idea?

**Comment by ge0rdi** [comment]
`Open-Shell` is meant to replace start button. Not to create additional start button.
So we don't plan to add any such functionality.
See #1237 for more info.

**Comment by Paril** [comment]
I know this was closed as not planned, but.. this behavior already works properly on multiple monitor setups:
!()[https://i.imgur.com/MYdgEIj.png]

I assume this part is a bug, but, this is also the behavior I'd like to have because the Classic Shell start menu is better for certain tasks, but it's nearly impossible to use if it's centered because the menu elements like to go off the side of the screen if you have more than three columns.

**Comment by JMD-tech** [comment]
I second that. Doing some kind of "manual binary chop" testing different versions, 
found the regression is between 4.4.180 and 4.4.181 version. 
Checking the changelog probably has to do with "Windows 11 start button support".

While i definately agree replacing the start menu button instead of adding another one is way cleaner, 
have to admit, that as Open Shell is meant to give back the much better "classic" UI, 
having an extra start button almost never used, is a much more acceptable annoyance than 
the start button with classic menu not being at the left of taskbar. 

The cleanest way to do this would be replacing also the whole taskbar, 
but that would make the whole project another order of magnitude of code and maintenance. 

Will try to compile and test differences, ideally see if we could have the "create another start button"
only if the "start button at left" is checked in preferences.

**Comment by Larsa2** [comment]
Follow this and it did work for me.

On your keyboard press windows key + I
It will open your settings and look for Personalization.
Click on it and on the left side look for taskbar.
Click on the taskbar and look for " Task bar location on screen"
There is a drop down box their and choose Bottom.

It will change the position of your task bar.

Close the settings and you should be all set.

**Comment by Larsa2** [comment]
![Uploading Skärmbild 2024-11-30 115129.png…]()
