### ISSUE TITLE
compiling setup: wrong WiX path in batch files

### ISSUE THREAD

**Issue by nikolasr** [Open-Shell/Open-Shell-Menu#1582]
### Describe the bug

When using the batch files in ./Src/Setup setup creation fails with current WiX build 3.14 installed.
This is because the path variable is set to match old version 3.11.

Solution: Change WiX path in all setup batch files from 
`C:\Program Files (x86)\WiX Toolset v3.11\bin\` to `C:\Program Files (x86)\WiX Toolset v3.14\bin\`

### Area of issue

Installation/Other

### To reproduce

Install WiX 3.14 and all other requirements and try to build setup binary using batch files. You'll get "file not found" errors.

### Expected behavior

successful compile

### Open-Shell version

latest git master

### Windows version

Windows 1022H2

### Additional context
VS used: 2022 community edition

**Comment by ge0rdi** [comment]
We are using `Wix 3.11` because that version is available in `Appveyor` images (used to build official `Open-Shell`).
I will update `BUILDME.txt` as it contains out of date info.

As a workaround you can add `C:\Program Files (x86)\WiX Toolset v3.14\bin\` to your `PATH` environment variable and it will work just fine.
