### ISSUE TITLE
separate open-shell and standard win 11 icons/buttons

### ISSUE THREAD

**Issue by eps696** [Open-Shell/Open-Shell-Menu#1593]
### Describe the bug

while ago (on win11 with 4.4.170) open shell menu was at the "classic" bottom-left position, while standard win 11 menu resided in their taskbar (closer to the center of the screen), so these two were clearly separated in space. 
after recent win 11 updates (KB5027231, KB5028185) and upgrade to 4.4.189 version, the open-shell menu effectively _replaced_ win11 start menu, as is now opened by the same icon and from the same position.

is it possible to move open-shell icon and menu back to the classic bottom-left (as it used to be)? 
or at least to separate it somehow with the standard win11 start button (so that one could launch these two menus just by mouse)?

### Area of issue

Start menu

### To reproduce

1) press hotkey for launching win11 start menu (e.g. shift-win) => menu is launched from its icon on taskbar. then press hotkey for launching open-shell start menu (e.g. "win") => menu is launched from the same place. 
2) no way to launch both start menus (win11 and open-shell) just by mouse, using different icons/buttons. extra keyboard shortcut must be used.

### Expected behavior

separate start button for open-shell menu at bottom-left of the screen

### Open-Shell version

4.4.189

### Windows version

windows 11, 22H2

**Comment by ge0rdi** [comment]
> open-shell menu effectively replaced win11 start menu, as is now opened by the same icon and from the same position

That's exactly what is the purpose of `Open-Shell` since its very beginning. To replace standard Windows start menu/button.
You can invoke Windows start menu by shift+click on start icon or shift+Win key combo.

> is it possible to move open-shell icon and menu back to the classic bottom-left (as it used to be)?

It used to be that way because `Open-Shell` didn't support Win11 and assumed that start button is located only on the left (as it was in Windows before Win11).
This was a bug and it was fixed in recent `Open-Shell` builds.

There is no plan to support separate `Open-Shell` button along with Windows one, as it makes little sense.

**Comment by eps696** [comment]
sometimes occasional failure or drawback is better than a planned feature ::] 
thanks for the prompt clarification.
