### ISSUE TITLE
VirusTotal Scan - 6 issues

### ISSUE THREAD

**Issue by pict0r** [Open-Shell/Open-Shell-Menu#1638]
### Describe the bug

![obraz](https://github.com/Open-Shell/Open-Shell-Menu/assets/46075912/3064bc9e-9e45-433c-b706-6c84535eef3a)

This app is unsafe. Has 6 security vendors. Makes my computer working slower.
Old classicshell is working well.

### Area of issue

Installation/Other

### To reproduce

.

### Open-Shell version

4.4.190

### Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment]
Thank you for your opinions.

> This app is unsafe. Has 6 security vendors.

Are you basing the claim on those dubious VT detections from dubious security vendors?
Or do you have anything concrete that you think the application is doing wrongly?

> Makes my computer working slower.

What exactly is slower?
Are you sure it is `Open-Shell` related? (e.g. disappears when `Open-Shell` is uninstalled)

If you can replicate such scenario, please, obtain [ETW trace](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-ETW-trace) so we can analyze it.

> Old classicshell is working well.

That is cool.
You are free to use any software you like.

**Comment by DrMoish** [comment]
At this date, 01 Aug 2023, there are eight alerts at VitusTotal for OpenShellSetup_4_4_190: Bkav,W32.AIDetectMalware, Cyren,W32/ABRisk.NLES-4551, APEX,Malicious, Cynet,Malicious, Rising,Trojan.Generic@AI.88, Trapmine,malicious.moderate.ml.score, Google,Detected, MaxSecure,Trojan.Malware.300983.susgen . Though I believe these are based on _behavioral analysis_ rather than finding an actual threat, I will not apply this update until that issue is fixed.

**Comment by ge0rdi** [comment]
> I will not apply this update until that issue is fixed

The only way to fix the _issue_ is to report this to those vendors as false-positive (as there is nothing malicious in `Open-Shell`).

And if they insist on being malicious, they should provide information about what exactly is considered as such so that we can do something eventually.

**Comment by Objectivite** [comment]
@ge0rdi 

Reporting to  VirusTotal  a false-positive is not the job of end-users, but that of the programmers, just to clarify the correct way of approaching this.  I write software and my answer to the posters above would have been more **user-friendly** saying something like _"Let me see what I can do by reaching out to VirusTotal"_.

8 reports still today.

![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/89191739/0ee3e1b5-fe61-4c2a-bd6c-fc9d41144b5e)

**Comment by ge0rdi** [comment]
@Objectivite 
Than you for you insights.

> Reporting to VirusTotal a false-positive is not the job of end-users, but that of the programmers, just to clarify the correct way of approaching this.

There is no point to report false-positive to VirusTotal as it is just aggregator of various scanning products:
https://support.virustotal.com/hc/en-us/articles/115002121185-I-am-experiencing-a-false-positive-my-file-or-site-should-not-be-detected-

The only way is to report the problem to all the vendors that do the wrong detection.
And this is not something I'd like to waste my time on.
I'm just trying to maintain this project in my free time. And the last thing that I want to do is to dispute bogus detections of crappy security products.

Thus if someone is worried about about those detections, he should approach those vendors (especially if he is using (paying for) their product. And ask them what exact malicious actions the software does.

> I write software and my answer to the posters above would have been more user-friendly saying something like ...

I'm sorry if what I wrote sounds unfriendly. I'm just tired of these constant crappy detections, not only in this project but I can see them in many other open-source projects.

I know how AV products work these days (as I'm working in the field). Most of them don't care about false-positives. They tend to detect any unknown files, and if one AV starts doing so others will gladly copy it. Then there is this machine learning hype (see all those crappy detections with `ML`/`AI` in name), this is another source of false-positives than not many care about.

> two are too serious to ignore : Google and Cyren

What to say. They are just wrong.

This whole project is open-source and transparent. Builds are done on AppVeyor and its images are unlikely to contain any malware (it would be revealed quickly as it is used by many more customers, for more important projects than this).

This project may do kind of _suspicious_ things as it injects into Explorer. But that's because it is the whole purpose of this project, to be able to customize Explorer and that cannot be done without injection/hooking.
All of this is clearly visible in source code and can be challenged at any time.

**Comment by ge0rdi** [comment]
> two are too serious to ignore : Google and Cyren

Note that they both don't flag `4.4.190` installer anymore.
So it was obviously a false-positive.

**Comment by Objectivite** [comment]
> > two are too serious to ignore : Google and Cyren
> 
> Note that they both don't flag `4.4.190` installer anymore. So it was obviously a false-positive.

**Thank You for monitoring this and getting back to us all on it.**

O.

**Comment by ge0rdi** [comment]
I think we can close this now as it is obvious those detections are just false positives.

In general, if somebody knows that there is something malicious in our code (it is available to anyone) he should report that so we can have a look. But without any such information there is not much to do.
