### ISSUE TITLE
Latest version opens menu at horizontal center on main monitor

### ISSUE THREAD

**Issue by Kairys** [Open-Shell/Open-Shell-Menu#1646]
### Describe the bug

I installed 4.4.190 and found when I open the menu on my main monitor it appears at the center of the taskbar instead of at the left corner. If I open it on my secondary monitor it is correctly positioned. 

I also note if I enable the custom button it ignores the "align to corner of screen" and appears also centered on the taskbar.

### Area of issue

Start menu

### To reproduce

Install 4.4.190.
Open menu.

### Open-Shell version

4.4.190

### Windows version

Windows 11 22H2

**Comment by ge0rdi** [comment]
>  it appears at the center of the taskbar instead of at the left corner

Do you use _center_ aligned taskbar? E.g. is the start button in the center of taskbar or on the left?
`Open-Shell` is supposed to display start menu just above the start button.

> I also note if I enable the custom button it ignores the "align to corner of screen" and appears also centered on the taskbar.

That option means something different.
Normally the custom button is vertically centered in task bar. With this option it is placed in the corner of original start button (that used to be corner of screen on older than Win11).

**Comment by Kairys** [comment]
Thank you for your reply.... It is not the placement of the button I question, it is the location of the menu. Until recently (sometime after 4.4.170) the menu always appeared above the left side of the taskbar, but now it appears above the center (on my primary monitor only)

**Comment by ge0rdi** [comment]
As I wrote, `Open-Shell` is supposed to display start menu just above the start button.
So where your start button is there should menu be displayed.

If you don't want it at center then you can use _left_ aligned taskbar (in Windows settings).

> Until recently (sometime after 4.4.170) the menu always appeared above the left side of the taskbar

That was because until recently we didn't support Windows 11 properly.
Before Windows 11 it was assumed that start button (and thus start menu) should be always in the corner of the screen.
Since Windows 11 it is possible to use _center_ aligned taskbar, so that the start button (and subsequently start menu) is located in the center of the screen.

**Comment by Kairys** [comment]
Okay, thank you for the explanation (although I wish it were otherwise ;)
