### ISSUE TITLE
When searching sometimes items overlap the "Search the Internet" list item

### ISSUE THREAD

**Issue by NoTouchingthePC** [Open-Shell/Open-Shell-Menu#1648]
### Describe the bug

After updating to Open-Shell 4.4.190, when searching for say, apps and features, when I type apps into the search box, the bottom search result is drawn on top of the "Search the Internet" listing. See screenshots. Currently using the new Immersive skin, 7 style start menu. (I haven't tried switching to either of the classic styles but I imagine the issue wouldn't be present in those styles.) Switching to the Metro skin only partially fixes the issue. The last search result displays further up but is still drawn partly on top of the internet search button. This is definitely an issue with Open-Shell and not the skins as this wasn't happening at all on 4.4.170.
![Screenshot (401)](https://github.com/Open-Shell/Open-Shell-Menu/assets/138227929/e0c3a1b8-10a6-4c9f-8f2e-79225b7cdba1)

### Area of issue

Start menu

### To reproduce

Open the start menu like normal.
type a fairly general search term into the search box like apps or something
Observe that the last search result is drawn partially on top of the internet search item.

### Expected behavior

For search results to not appear on top of the internet search button as it looks weird and messed up.

### Open-Shell version

4.4.190

### Windows version

Windows 10 22H2

### Additional context

Was *not* happening on Open-Shell 4.4.170 (the version I previously had installed.)

**Comment by ge0rdi** [comment]
I wasn't able to replicate it so far :(

Please, attach your `Open-Shell` configuration XML.
Maybe it is related to some settings you have.

**Comment by ge0rdi** [comment]
Thank you.
Here are steps to replicate it:

- start with clean `Open-Shell` installation (Windows Sandbox)
- disable `Show recent or frequent programs`
- disable `User files` (or some other item) in `Customize start menu`
- disable `Search files`
- disable `Enable "See more results" option`
- open start menu and search for `apps`

This will make menu height smaller than by default. And then it seems number of search items is wrongly calculated so that the last item overwrites "Search the internet".
I'll try to have a look at it.

**Comment by NoTouchingthePC** [comment]
Yeah, I have all of those disabled except for search files but I have the search indexer service in Windows disabled. In the second column Devices and Printers, Default Programs, and Help are disabled. I actually have reenabled the see more results button and yep. Problem is solved (at least on the Metro skin). But now when I search, after it finishes loading the results, there actually isn't a see more results button. Odd.

**Comment by ge0rdi** [comment]
@NoTouchingthePC 
I've fixed the search result overlapping.
You can try with latest build from #1636 PR.

It should now work correctly in all cases.

> But now when I search, after it finishes loading the results, there actually isn't a see more results button.

That is because of disabled indexer service.
`See more results` uses indexer to show more results. So if indexer is disabled this doesn't work and thus it makes no sense to show such option.

**Comment by ge0rdi** [comment]
I have also fixed another issue (that was introduced with option to disable "See more results" item).
The `Searching...` indicator (that indicated search in progress) was also disabled if "See more results" was disabled.

I believe this was not proper change as those are two unrelated things.
`Searching...` should be shown when there is search still in progress, no matter of settings.

**Comment by NoTouchingthePC** [comment]
> > But now when I search, after it finishes loading the results, there actually isn't a see more results button.
> 
> That is because of disabled indexer service. `See more results` uses indexer to show more results. So if indexer is disabled this doesn't work and thus it makes no sense to show such option.

Okay, that makes sense.

I installed the build and now search works as normal. No overlapping of listings. Thanks! 👍

**Comment by ge0rdi** [comment]
Fixed in `4.4.191`.
