### ISSUE TITLE
Start Menu option "Align to the corner of screen" not working

### ISSUE THREAD

**Issue by entic207** [Open-Shell/Open-Shell-Menu#1689]
### Describe the bug

I'm trying to separate both start menu and use only the Open Shell instead of the windows native. but after the last update (4.4.190) I can't set it at the left side of the taskbar.
![Captura de tela 2023-09-01 034657](https://github.com/Open-Shell/Open-Shell-Menu/assets/143785375/e5ee3f57-aaea-4819-b55a-917609bfe39e)

### Area of issue

Start menu, Taskbar

### To reproduce

1. Go to Startt Button Advanced Settings
2. Toggle "Align to corner of the screen" as marked.

### Expected behavior

![Captura de tela 2023-08-21 070157](https://github.com/Open-Shell/Open-Shell-Menu/assets/143785375/21217600-630b-4f2e-8be1-8dabfd83c53b)

### Open-Shell version

4.4.190

### Windows version

Windows 11 22H2 (OS Compilation 22621.2134)

**Comment by ge0rdi** [comment]
The _expected_ behavior you described is unfortunate result of bug in older `Open-Shell` versions that didn't support Windows 11 properly.
`Open-Shell` was always meant as start menu/button replacement.

You can find more on this topic in #1252 discussion.

`Align to corner of the screen` option wording is a bit unfortunate because it suggests something else than the option is (ald always was) doing.
It was clarified in #1673 and the option will be renamed in next version to reflect its real intent/purpose.

**Comment by entic207** [comment]
I found a Way to “correct” this with image editing. Thank you

Em sáb., 2 de set. de 2023 14:53, ge0rdi ***@***.***>
escreveu:
