### ISSUE TITLE
Windows Defender is trying to block Open-Shell

### ISSUE THREAD

**Issue by NoTouchingthePC** [Open-Shell/Open-Shell-Menu#1691]
### Describe the bug

I recently reinstalled Open-Shell, and upon running the installer which I downloaded straight from GitHub I got the message seen in the screenshot below:
![Screenshot (145)](https://github.com/Open-Shell/Open-Shell-Menu/assets/138227929/f80c5139-73d2-43c6-a257-2a4bd8849d29)
It would appear that Microsoft is [once again](http://classicshell.net/forum/viewtopic.php?f=7&t=3349#p15624) trying to block Open-Shell on Windows 10.

### Area of issue

Installation/Other

### To reproduce

Download latest Open-Shell from Releases here on GitHub.
Run Open-Shell installer from your downloads folder
Observe the warning screen seen above in my screenshot

### Open-Shell version

Idk. Only tested with 4.4.191.

### Windows version

Windows 10 latest build, maybe Windows 11 too

### Additional context

I didn't observe this happen until just today when I reinstalled Open-Shell. After hitting Run anyway (which only shows when you click more details) it went just fine. I _am_ a little worried about the fact that Open-Shell still isn't signed, too, since we're on the topic of security. And this could also just be my antivirus being overly paranoid.

**Comment by A-Right-Git** [comment]
On my version it keeps crashing the taskbar, so I have to uninstall... :/

**Comment by ge0rdi** [comment]
@NoTouchingthePC 
Unfortunately, Defender (Smart Screen) is blocking unknown new binaries from running. It will lift the block after few days typically.
If you have downloaded the installer from official site (github) then you have nothing to worry and can just select `Run anyways`.

There is not much we can do about it at the moment :(

> I am a little worried about the fact that Open-Shell still isn't signed, too, since we're on the topic of security.

This project is maintained by volunteers in their free time. Signing certificate costs something, plus there has to be some signing infrastructure needed (that will hold private key securely and sign binary during the build process, which is also not for free.

> And this could also just be my antivirus being overly paranoid.

You can still report such false-positives to Microsoft, so that they can examine the binary and lift any blocks as it contains no threats.

**Comment by ge0rdi** [comment]
@A-Right-Git 

> On my version it keeps crashing the taskbar, so I have to uninstall... :/

If you are experience crashes related to `Open-Shell` you can try to obtain crash dump using steps from https://github.com/Open-Shell/Open-Shell-Menu/issues/1263#issuecomment-1365287057.

Once you have dump, please upload it somewhere and create new issue with link to the dump.

**Comment by NoTouchingthePC** [comment]
Okay. So this is really Microsoft being paranoid. Thanks. Once I click Run
anyway, it never shows that popup again.
