### ISSUE TITLE
Win10 1903 compatibility

### ISSUE THREAD

**Issue by truthsword** [Open-Shell/Open-Shell-Menu#170]
I upgraded to Win10 1903 today and wondered if Open-Shell is compatible. I noticed that most of the Win Apps would not launch (ex., Weather, Microsoft News, Alarms & Clock... Has anyone run into this?

Discovering another issue, I rolled back to 1809, so I can't test again for a few weeks.

**Comment by ge0rdi** [comment]
I'm using `Open-Shell` on Windows 10 1903 and haven't noticed any issues.

**Comment by CTVCAM8** [comment]
I have just upgraded to Windows 1903 as well. 
No crashing apps. On one app I was asked to verify my Windows password to get access.

If using Classic Shell Menu, glass menu color does not work anymore. Only menus that use designated "Metro" colors like the Metro skin work.
Skins like Smoked Glass, Windows Aero are now always dark grey, devoid of color.


Open-Shell appears to have fixed Glass capability and is enabled again.

Thank you very much. :) :) :)

ps.
I have commented on Classic Shell forum about this glass feature matter

**Comment by ibuprophen1** [comment]
The following article may be helpful regarding the Built-in windows start menu changes on the 1903 update. 

https://news.softpedia.com/news/how-microsoft-improves-the-start-menu-in-windows-10-version-may-2019-update-525707.shtml 

Just an FYI... 


~Ibuprophen

**Comment by CTVCAM8** [comment]
There is one thing I'd like to mention about going back and forth between 1903 and 1809 upgrades, and then to 1903.
If you have to go back to 1809 for some reason, 
(common one - some folder locker programs make files inaccessible even in safe mode), 
uninstall Open-Shell, then do Windows old update recovery 1809.
I didn't do that. What happened is Open-Shell went zombie on me.
Windows had decided to strip away the MSI installer part.
I could not find any way to either reinstall or uninstall. Revo uninstaller did not help.
I had to go into the registry and delete all Open-Shell entries. Then I could install again. 
I never had a problem with Classic Shell program. 

Whew!

**Comment by klepp0906** [comment]
im using it without issue EXCEPT it now hangs on open every once in awhile.  No idea why, never did it before.  Its almost like it goes to sleep like a hard drive you dont use for awhile.  Clicking on it takes a few seconds to open, after that its kosher.  /shrug.  dont like it, but havent the slightest on direction as to how to address it.  

could be 1903 related, I imagine a new artifact will go up eventually :P

**Comment by ge0rdi** [comment]
@klepp0906 If you are able to replicate the _lag_, you can create ETW trace from time when it occurs:

- run `wpr -start GeneralProfile` from administrator console
- wait until _lag_ happens
- then save trace using `wpr -stop trace.etl`

Upload _trace.etl_ somewhere, I can have a look.

**Comment by ibuprophen1** [comment]
I'm just wondering if this is related to the https://github.com/Open-Shell/Open-Shell-Menu/issues/158? 


~Ibuprophen

**Comment by tcja** [comment]
I'm experiencing only one issue so far since I updated to 1903, when hovering quickly over the "All programs" button it will active it straight away which is quite annoying since the normal behavior to active that button is a hover of about one second, now each time I wanna click on a pinned icon shortcut I can't hover my mouse over "All programs", I have to avoid the button to not trigger it. Anybody knows a workaround for this?

**Comment by ge0rdi** [comment]
@tcja 
This doesn't seem to be related to 1903.
`All Programs` folder is automatically expanded on hover after some time.

There is a setting called `Delay multiplier for the All Programs button` that controls the time. It is percentage of `Menu delay` time.

It seems there is no way of disabling this completely (even if `Menu delay` is 0, value 100 is used).

Though  you can set that delay multiplier to big enough value (say 1000%) so that the folder won't be expanded quickly.

**Comment by tcja** [comment]
@ge0rdi 
Thanks very much for your input! Setting `Menu delay` to 32 ms fixed my issue but I still find it quite odd that I have to do this manually since my update to 1903, I never had to mess with that option (that I never heard of until you mention it) before.

**Comment by ibuprophen1** [comment]
Please correct me if I'm wrong @tcja... 

Are you asking about a default change to the "Menu Delay"? 

If so, It would be catering to the Windows 10 specifically and I don't believe that this would really help those with other Windows versions. 

Look at it this way... Each individual has their own Windows version customized along with their own flavor of the Open Shell Software installed. 

When something is customized, this typically includes the possibility of having to change one or more of the various values. 

This is why those are available to the individual user to make the appropriate changes needed to work for them. 

If the default value affects the majority of the users, then that would prompt the developer(s) to take another look at those values for a possible change to its default. 

I hope that I had explained this okay via text... 👌 

On another note... 

Am I correct in assuming that this issue, opened by @truthsword, has been resolved since that individual hasn't made any follow-up messages regarding this issue? 



~Ibuprophen

**Comment by truthsword** [comment]
Yes. I will close issue.

Regarding the menu timing mentioned above... a registry change will handle that. See here
<https://mywindowshub.com/how-to-change-menu-show-delay-time-in-windows-10/>

**Comment by ibuprophen1** [comment]
Thank you very much for following up with this @truthsword! 🎉


~Ibuprophen

**Comment by klepp0906** [comment]
> @klepp0906 If you are able to replicate the _lag_, you can create ETW trace from time when it occurs:
> 
> * run `wpr -start GeneralProfile` from administrator console
> * wait until _lag_ happens
> * then save trace using `wpr -stop trace.etl`
> 
> Upload _trace.etl_ somewhere, I can have a look.

good info.  learn something new every day.  Admittedly not high priority atm, have a TON going on.  But the lag is consistently a thing, so ill get it up at some point.

thank you
