### ISSUE TITLE
Ive done everything and its not working

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [Open-Shell/Open-Shell-Menu#1803]
### Describe the bug

I've tried using windows uninstaller to uninstall it. didn't work. i removed EVERYTHING from the folder, 2 .dll files still there and the GOD DAMN START MENU DIDN'T GO AWAY, PLEASE HELP!

### Area of issue

Start menu

### To reproduce

uninstall from windows uninstaller

### Expected behavior

what do you think.

### Open-Shell version

4.4.170

### Windows version

22H2

### Additional context

F***ING HELP.

**Comment by ge0rdi** [comment]
First of all, please, refrain from any rude language. Otherwise nobody will be interested in helping you and you may get blocked without any further warning.

> I've tried using windows uninstaller to uninstall it. didn't work.

Did it report some error? Or what happened?

You can use our [Utility](https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v4.4.191/Utility.exe) to manually uninstall `Open-Shell`.
Just run it and select option for manual uninstall.

**Comment by N0VA-The-Git-User** [comment]
sorry, i was a bit stressed out lol, will see if it works.

**Comment by N0VA-The-Git-User** [comment]
the utility wor
