### ISSUE TITLE
Screen all blue during installation of Open-Shell 4.4.191

### ISSUE THREAD

**Issue by Heng-Zhou** [Open-Shell/Open-Shell-Menu#1810]
### Describe the bug

During the installation of 4.4.191, the installer tried to automatically close File Explorer. After a long wait, it pops up a error message saying it can't close all applications. Then it seems that the installation succeeds, but the screen is all blue, and the only application I can see running is the FireFox browser so that I can submit this ticket.

### Area of issue

Installation/Other

### To reproduce

1. Download Open-Shell 4.4.191 (OpenShellSetup_4_4_191.exe)
2. Install it.

### Expected behavior

Install without any errors or blue screen.

### Open-Shell version

4.4.191

### Windows version

1803

**Comment by ge0rdi** [comment]
If there are some `Open-Shell` files still in use (typically the shell extension) then MSI installer will attempt to restart Explorer in order to free such file references (so that uninstallation can finish).

It appears that MSI fails to do that randomly (there were similar random reports, I think I have seen it once too, but cannot replicate at will).

In such case you can press `Ctrl+Shift+Esc` to start Task Manager and from it you can start Explorer.
That should then cause uninstallation to finish.

Not sure what else we can do here as it is built-in MSI functionality that handles this.

**Comment by Heng-Zhou** [comment]
If it is out of your control, let's grin and bear it.
