### ISSUE TITLE
Getting an error while trying to install latest 4.4.191 build

### ISSUE THREAD

**Issue by MarvellusL** [Open-Shell/Open-Shell-Menu#1892]
### Describe the bug

Can you please advise why I am running into an issue when trying to update Open-Shell. I get the attached error.
"Failed to extract setup file. 'C:\ProgramData\OpenShellSetup64_4_191.msi.'

My Open-Shell is installed here: C:\Apps\Utils\Open-Shell

Thank you.
![Error](https://github.com/Open-Shell/Open-Shell-Menu/assets/165818383/85a50adc-4a5a-4f21-bb52-71d4d082ba01)

### Area of issue

Installation/Other

### To reproduce

Go to Downloads folder and install 4.4.191.Exe

### Expected behavior

To start and complete installation.

### Open-Shell version

4.4.188

### Windows version

WIN 11 v23H2

**Comment by ge0rdi** [comment]
Installer is trying to extract MSI so that it can run it to install new version.
Apparently it was unable to create that file in `C:\ProgramData`.

Check if you have permissions to write there and enough disk space.
By default all users should be able to create new files in `ProgramData`.
Eventually, try to run installer as admin (MSI will require elevation either way).

**Comment by MarvellusL** [comment]
Hi,
Thanks for getting back to me so quickly. Running as *Admin* did the trick.
It's really weird as my machine is a standalone, private machine that I
have full admin rights to and that's why it never occurred to me to try
running in elevated mode.

Cheers.
Marcellus
