### ISSUE TITLE
Any updates for 2019 for Open-Shell?

### ISSUE THREAD

**Issue by indyjonny** [Open-Shell/Open-Shell-Menu#192]
I am a long time user of Classic Shell & currently using Open-Shell.  I haven't seen any updates for 2019.  Any updates/bug fixes/enhancements for 2019 yet for Win 10 users?

**Comment by ibuprophen1** [comment]
I just realized this as well... 

Under the "Releases" area within Github, it reflects v4.4.131 and I'm just curious if @ge0rdi or @coddec plans to provide any more releases there? 

I've been looking at another location for the releases and haven't really looked on Github itself (as I should be as well). 

@indyjonny, if you want, you can always use the Nightly Builds... 

The following is a link to the latest one (v4.4.139).... 

https://ci.appveyor.com/api/buildjobs/fhi8uec40tqhi16k/artifacts/OpenShellSetup_4_4_139-gccfsqel.exe

... Please let us know if you encounter any problems with it too. 

Personally, I believe that the latest Nightly Build is pretty stable enough for it to become an official release (though, this is not my sole call as the others would have to make this specific call as well). 

Thanks a Bunch! :-) 


~Ibuprophen

**Comment by blackcrack** [comment]
> 
> Personally, I believe that the latest Nightly Build is pretty stable enough for it to become an official release (though, this is not my sole call as the others would have to make this specific call as well).
> 
> Thanks a Bunch! :-)
> 
> ~Ibuprophen
Hi @ibuprophen1 

me too, the same procedure . aaand i see the public too, they need news.. and any news is good, to make news around the project.. and is give no news, is the project die ..in the public and the peoples turn elsewhere .. and if i see this bullshit dark website of Open Shell , can you kick the whole project in the trash, because there be only a couples programmers on it and there is no really interesting running stuff on it, because it's in the dark.. like the Webside .. https://open-shell.github.io/Open-Shell-Menu/

no "Day-colors" and no Screenshoot's and pictures of the program.., all dark, letters only and hackers like.. and this is bullshit .. in the public ...
so can you kick the project in the trash in the same step !
and how i have see, is the girly with the cat-ears gone also.. (good so !!)

so, we need releases, any release is a good release , because it's goes forward and any less release is a step back.. in the oblivion.., so @ge0rdi @coddec , give the whole release, if is also only one codepart,
this is shit no matter , it is a new version !!! and it is news and information around the project in the public and makes it interesting for the public !

so, have you a release, kick it out ! and you become a feedback, this makes more fun, this makes more interesting to make a new release for testing and the same step for the public.. 

all what it moves, lives, so, make it lived !!

best regards
Blacky

**Comment by ge0rdi** [comment]
I guess we will do release when there will be something substantial added/fixed.
