### ISSUE TITLE
Search box not searching 'Settings' - Win 11 24H2

### ISSUE THREAD

**Issue by H3X1C** [Open-Shell/Open-Shell-Menu#2033]
### Describe the bug

When searching for terms such as 'update' or 'display' I do not get setting results.
![image](https://github.com/user-attachments/assets/50fed7f3-62ce-4a3e-8bf8-722344f2607b)
I would expect to see settings items for Windows update and Display options etc.

In the settings I have the 'Search Settings' ticked under the 'Search Box' menu:
![image](https://github.com/user-attachments/assets/928714a6-227d-4600-b19b-0358fdfb636c)

Any help is appreciated, thanks!

### Area of issue

Start menu

### To reproduce

1. Go to the start menu
2. In the search box search for a settings related item e.g. update
3. No settings related items are shown in the search box

### Expected behavior

I would expect to be able to search on settings items e.g. search 'update' and see a result for Windows Update

### Open-Shell version

4.4.191

### Windows version

Windows 11 24H2 (26100.2314)

**Comment by ge0rdi** [comment]
Thank you for reporting. I can confirm the issue.

Apparently the XML with all settings changed name since 24H2.
Previously there was this file:
`%windir%\ImmersiveControlPanel\Settings\AllSystemSettings_{253E530E-387D-4BC2-959D-E6F86122E5F2}.xml`
Now it seem there are two (similar) files:
`%windir%\ImmersiveControlPanel\Settings\AllSystemSettings_{D6E2A6C6-627C-44F2-8A5C-4959AC0C2B2D}.xml`
`%windir%\ImmersiveControlPanel\Settings\AllSystemSettings_{FDB289F3-FCFC-4702-8015-18926E996EC1}.xml`

We should try to parse new file (if exists) and fall-back to old one.
