### ISSUE TITLE
"Navigation Pane Style" setting not working...

### ISSUE THREAD

**Issue by tester2011** [Open-Shell/Open-Shell-Menu#209]
Hi Guys,

Running Win 10 Pro 1903 64-bit, Open Shell 4.4.131 and just noticed that the navigation pane style is no longer showing the old "XP Style" (with the dotted-lines linking the various directory/sub-dir labels - also has a bigger indents for menus/subs).

Changing the setting from either of the two options - "Windows XP Simple" or "Windows Vista" - has no effect.

Cheers,

Mike.

**Comment by tester2011** [comment]
My mistake - issue resolved!

**Comment by ajawamnet** [comment]
How did you resolve that?  I have one win 10 pro box that shows XP classic and one that does not. Both machines were built from shrink wrapped Windows 10 Pro Install CD's I fucking hate Windows 10...

**Comment by Ibuprophen** [comment]
@ajawamnet, I understand how you feel regarding Windows 10 as I'm not a fan of it either, but can you please keep the language clean.

I had edited only 1 of your words and, please keep in mind, that I have "very rarely" edited a comment made by anyone and would "only" do so if the language, word(s), statement(s), etc... was/is either not appropriate or threatening to others. 

With that stated/clarified... 

Regarding your question, can you please elaborate further regarding your specific issue? 

I'm just thinking that your issue may appear to be the same/similar, but since it's a very different version of Windows, it may likely be tied to something completely different. 

I may just ask you to open a new issue as this has been closed/resolved by another individual. :-) 

Thank you very much for your time, patience and understanding with this. 


~Ibuprophen
