### ISSUE TITLE
Open-Shell-Menu 4.4.131 : Error downloading Images?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [Open-Shell/Open-Shell-Menu#213]
hi. nice proggy :)
But now, when opened 200 tabs and 2 Browsers, i can see who is guilty on dragging down my computer when saving pictures by rightclick: it's Open Shell Menu o_O

Whenever i want to save an image the WHOLE explorer seems to be reloaded.
The taskbar is being rebuilded BEFORE the save dialogue appears. 
That costs time...

I can see it clearly now because everything runs slower because of my "Powerusing" ;)
So you can see that a fast CPU or less CPU-drag could hide an software error...

Evidence: I stopped Open Shell Menu and the Windows 10 Menu-Thing runs much faster and savings happen at once.

So what is the error?
Please help.
thx :)

**Comment by Ibuprophen** [comment]
When heavily running so much (ie... software, window dialogs, etc...), your actually reaching/surpassing the limitations of, both, your Processor Core(s) and the available RAM (that your system earmarks for the pertinent items required to run your OS). 

This is not to mention the load on your HDD as it also has limitations like, primarily, the data rate transfer. I can just imagine how fragmented your HDD is... LOL! 

With that being stated... 

What you had experienced is in no way an issue with the Open Shell Software. The system will, by design, to heavily/try to keep the pertinent files and such specific to the system to keep them running in a prioritized way. Your system, basically, sees this resource demand and it systematically compensates. This is why it runs better by stopping the programs/services you had mentioned because the resources set for them opened up as being available for others. 

I hope that I had explained this okay via text... :-O 



~Ibuprophen

**Comment by Clemens-Ratte-Polle** [comment]
No, my HD is not fragmented.
RAM ist under 50% Use.

The question is:
What have 200 Tabs - most of them suspended - to do with Explorer.exe and OSM in the Browsers Open- and Save-Dialogue?
Is it typical that Explorer.exe checks ALL tabs?
thx

**Comment by Ibuprophen** [comment]
Explorer.exe is a windows shell that manages software that requires a GUI (Graphical User Interface) that includes (but not limited to) the Start menu, Taskbar, Desktop Environment, File Manager, etc... 

Though, this isn't a dependency for the Windows OS to operate, but it's vital to everything that runs with any form of a GUI on Windows. 


~Ibuprophen
