### ISSUE TITLE
[feature request] Start button & menu on the right

### ISSUE THREAD

**Issue by rinaldi6109** [Open-Shell/Open-Shell-Menu#224]
Is it possible to have the start button & menu on the right side of the screen? 
Is it possible to have it quickly manipulating some registry entries?

**Comment by Ibuprophen** [comment]
You should be able to do this... 

First you right click a blank/unused part of the taskbar and then unchecking the "lock the taskbar" option. 

Then place your cursor on the start menu button and then, by using left click on the mouse, "press & hold" (very important) then drag it to the right side of the task bar and then release the mouse button. 

You'll notice the concept of this type of movement there and just tweak (by the press, hold & dragging) the positions to your liking. 

After your done, just right click again on a blank/unused part of the taskbar and then check off the "lock the taskbar" option to lock the positions in place. 

It's simple but, I hope that I had explained this okay via text... :-) 

Hopefully, If/when your all set, please let me know and then you can close this issue. 



~Ibuprophen

**Comment by rinaldi6109** [comment]
Sorry but  I could not move the start button by drag&move as you have explained.

**Comment by Ibuprophen** [comment]
Hmm... I believe that your probability on Windows 10 (which would have been helpful to know)... 

I know that there's some small tools on a few trusted websites that are specific to tweaking the taskbar. 

I'll need to do some digging around to provide the link(s) to you. 

The thing is, the Open Shell Software is specific to the Start Menu and isn't really for customizing it's specific location (moving the menu itself). 

It's just been a little while since I've done this type of customization myself. 


~Ibuprophen

**Comment by rinaldi6109** [comment]
I tried both on Win 8.1 and on Win 10.

**Comment by Ibuprophen** [comment]
@rinaldi6109, My apologies for the delay...

I had discussed this with a friend of mine and he had mentioned the following (i had forgotten about)...

https://www.thewindowsclub.com/orb-mover-move-start-button-menu-windows

...it states for Windows 10 but, he had stated that it should work for Windows 8 - 10 as well.

The following 2 provides unique options that may help you out as well.

https://www.tenforums.com/tutorials/68038-set-menus-open-aligned-left-right-windows-10-a.html

https://www.thewindowsclub.com/ultimate-windows-tweaker-4-windows-10

I just can't state if anything works for Win10 because i don't have Win10 installed (yet) on my other PC as well as my suffering from OMMS (the Old Man Memory Syndrom... LMAO! ).

I hope they were helpful and Good Luck! :-) 


~Ibuprophen

**Comment by rinaldi6109** [comment]
Orb mover is an abandoned project and it doesn't work on Win 8.1 and 10 (I haven't win 7 anymore).

**Comment by Ibuprophen** [comment]
As I had stated... 

`I just can't state if anything works for Win10 because i don't have Win10 installed (yet) on my other PC as well as my suffering from OMMS (the Old Man Memory Syndrom... LMAO! ).`

I remember using the Windows Tweaker tool just after Win8 was released but, I think it was called `TweakUI` at the time. That was an amazing tweaking tool for a bunch of little things in Windows. 

The thing is that I've never, personally, even wanted to move the Start Button (specifically) myself. 

Though, the topic for this thread is a very good (and unique) feature request, the primary function of the Open Shell Software is to replace and customize the default Windows Start Menu/Button. 

Anything else this software currently does that's not necessarily specific to the start menu is only an added bonus brought over from the original Classic Shell itself. 


~Ibuprophen
