### ISSUE TITLE
Move Settings link above Control Panel

### ISSUE THREAD

**Issue by DragoCubed** [Open-Shell/Open-Shell-Menu#23]
You get why at this point. And again, this is totally possible manually but it should be like this by default because Windows 10 has many settings in the settings app.

**Comment by ge0rdi** [comment]
You can change order of menu items in `Open-Shell settings` -> `Customize Start Menu`.

**Comment by DragoCubed** [comment]
@ge0rdi 
this was about defaults :(

**Comment by NebelNidas** [comment]
@ge0rdi I think @DragoCubed is right. As more and more settings are moved towards the Settings app, removing them from Control Panel, latter is increasingly getting less and less important, especially since many of its entries now only point to the new settings anyway. It just doesn't make sense anymore giving them a higher priority than the new entries.

**Comment by NebelNidas** [comment]
This also applies to search results, not just the shortcuts in the start menu.

**Comment by NebelNidas** [comment]
Oh, I just created a new issue for this: #481 😅

**Comment by DragoCubed** [comment]
@NebelNidas dw that's not a duplicate. you're referring to search results and i'm referring to the shortcut :)
