### ISSUE TITLE
Classic Start Menu crashing explorer.exe on Windows 10 Enterprise x64 Build 17134

### ISSUE THREAD

**Issue by DouglasBissoli** [Open-Shell/Open-Shell-Menu#247]
Greetings!

Open Shell keeps my explorer.exe restarting every time it initializes.

I have compiled the latest version of Open Shell Menu from the commit on 10/26/2019 and also tested it with the latest release, from 09/29/2018 (4.4.131).

I just made a crash dump using **procdump**, following the [instructions from the old Classic Shell forum](http://www.classicshell.net/forum/viewtopic.php?f=12&t=6):
[explorer.exe_191102_103339.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/3800544/explorer.exe_191102_103339.zip)

And here is the **windbg analyze**: [windbg_analyze.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/3800561/windbg_analyze.txt)

My explorer.exe only initializes correctly when I terminate the StartMenu process in the task manager.

My specs from CPU-Z: [cpu-z.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/3800560/cpu-z.txt)

Thank you.

Best Regards,
Douglas Bissoli.

**Comment by ge0rdi** [comment]
The crash comes from `igfxCPL.cpl` (Intel graphics related). But it is unclear why it crashed as the stack trace cannot be obtained.

Could you upload file `C:\Windows\System32\igfxCPL.cpl` from your machine somewhere? It may help with obtaining stack trace.

Also please install official `Open-Shell` and provide dump from that, so that we have proper symbols.
