### ISSUE TITLE
Open Shell locks up and wakes up all the hard drives

### ISSUE THREAD

**Issue by xendrian** [Open-Shell/Open-Shell-Menu#252]
There is an issue with open shell on computers, that use multiple hard drives.

OS + Open Shell on system SSD
Generic random data on two HDD's

When the start menu is opened, it locks up until the hard drives are spin up. 
Also because it could cause long term damage, when the hard drives are always spinning up, when 
i open the start menu.  After closing the menu, the hard drives will go into sleep mode again, after a few minutes of non-usage. 

Please fix this, so the hard drives will remain in sleep mode, when using the start menu.

**Comment by Ibuprophen** [comment]
I can't reproduce this. I've got 3 HHD's on one of my towers and 2 on one of my laptops without any issues... 

~Ibuprophen

**Comment by ge0rdi** [comment]
@xendrian 
Most likely Start menu is touching some files on those drives.
Try to create [Procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) log, so that we can see what files it opens (and possibly why).

**Comment by XenHat** [comment]
Most likely related to #45

**Comment by Ibuprophen** [comment]
I'm inclined at thinking that this is either/or the Windows Indexing and/or the capacity/fragmentation of the HDD's as well. 

~Ibuprophen

**Comment by xendrian** [comment]
I don't really know, how procmon works,
but i get this, when i open the menu: 

There are only files on C, which is the SSD, and for me it does nox explain the problem with the 
hard drives. Because they should stay in sleep mode.

**Comment by xendrian** [comment]
I don't know how exactly procmon work. 
But i do get this, when i'm opening the menu: 
https://imgur.com/a/Tf1lKVc

These are all files on C, which is the SSD

**Comment by ge0rdi** [comment]
@xendrian 
Right-click on `explorer.exe` and select `Include 'Explorer.exe'` to filter records from explorer.

Then use `Tools -> File Summary...` to see all accessed paths.
And check if there is some path on different disk than `C:`.

**Comment by klepp0906** [comment]
same issue.   was this ever resolved?  Not sure if its related to driver or what but my external spins down fast, regardless of setting within windows.  I presume due to something detecting it as external and it having its own timer.

Nonetheless.  Accessing start ultimately soft-hangs while it spins it up.  (presumably the rest of my drives too, but it only seems to hang when it comes to spinning up the external as if i have that one shut off it doesnt happen)

**Comment by klepp0906** [comment]
Seems it is only happening when "Show recent or frequent programs" is set to Frequent.  Does not happen when set to Recent.

unfortunately Frequent is my preferred.

I did start up procmon but neither option is showing access to anything on D: which is the drive its spinning up causing the hanging.

**Comment by xendrian** [comment]
@geordi 
i still have classic (or now openshell) on my seconday pc and there is still the same issue. 
There aren't any paths, i believe it has to do with some windows search related issue, 
that it spins up those hard drives,  to make the search bar respond faster, but it's just a guess. 

I also do have my Music and Video folders on these hard drives included into my windows media libraries, so they will show up in media player programs. 

On my main PC i switched over to another start menu replacement program, which does not have this issue so far, but is paid.

**Comment by klepp0906** [comment]
i did try the switch to start10 as a potential option to circumvent some of the issues open-shell has.   I found it fall short in a lot of areas that are important to me unfortunately.  So the struggle continues ^

**Comment by klepp0906** [comment]
yea through more testing, been purging and trying new drivers - anything to find a reasonable workaround.

Disabling metro apps still doesnt resolve it.  If i open the menu after my external sleeps with "frequent programs" checked it will hang and spin it up.

I have to use recent programs.  whatever kinda cach'eing its doing is reaching far n wide.  procmon shows it mucking with keys here 

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{CEBFF5CD-ACE2-4F4F-9178-9926F41749EA}

which makes sense as thats where it tracks usage i believe.

Still more testing to be done to find the best way around this non programmaticaly until someone with the required skillset and motivation attacks it :D

**Comment by garygreen** [comment]
I'm also having this problem. Hard drives that power down due to inactivity (Power Management settings in windows) are spun up when OpenShell opens - there is a noticeable lag/freezing of the menu until hard drive is fully spun back up. I don't understand why it needs to do this.

Even if OpenShell tries to access files on that spun up drive - the question is, why? Shouldn't all the start menu entries be cached in memory, or at least in one file that it accesses without the need for looking through various drives?

The "Show recent or frequent programs" set to Recent didn't work for me, it still spins up drives which shouldn't be needed to show the menu or search for programs it's already cached.
