### ISSUE TITLE
Virus Detection?

### ISSUE THREAD

**Issue by harrismail** [Open-Shell/Open-Shell-Menu#269]
Not a "bug" as such but I thought this might be of interest...
I just uploaded the latest release of Classic Shell v4.4.142 to the Virus Total website www.virustotal.com and three AV engines detected some anomalies with the setup file? I always upload new exes to check them out but interestingly the last release v4.4.131 did not have any issues when uploaded to Virus Total?
Thoughts?
![Virus_Total](https://user-images.githubusercontent.com/34132327/70388748-d01fc100-19ad-11ea-817d-1acb109a03f1.JPG)

**Comment by Ibuprophen** [comment]
Relying on third party websites like this is extremely unreliable. They make their money by providing computerized (automated) biased results based upon the "Possibilities" factors without rhyme to reason. 

If anyone feels that this software may, might, will, etc... cause harm to their system, then by all means, don't use it. 

The small group of us on the developmental team provides this continuing development on a voluntary basis and any financial contributions/donations we receive is only used for any costs that are incurred related to this development. 

I would like to ask everyone to please not report this type of information from websites like this since it's becoming a repetitive response by us. 

Thank you very much for your time, patience, understanding and especially your support for the Open Shell Software. 


~Ibuprophen
