### ISSUE TITLE
Settings migration, import and Export 

### ISSUE THREAD

**Issue by ibuprophen1** [Open-Shell/Open-Shell-Menu#28]
Is there a way to implement a type of Classic Shell to Classic Start Migration?

**Comment by XenHat** [comment]
I'm sorry, what? @ibuprophen1

**Comment by ibuprophen1** [comment]
@XenHat, sorry about that... LMAO! 

I accidentally clicked on the submit button before I was finished.

**Comment by XenHat** [comment]
Definitely possible.
I thought about it and I did intend to implement settings migration, I simply haven't gotten the time to do that yet.

**Comment by ibuprophen1** [comment]
Thank you very much! :-) 

I tried to import the settings that I had backed up from the predecessor (Classic Shell) and probably 50% +/- imported fine in various areas of the Start Menu. 

I knew that this wouldn't work but, I even attempted to install the Classic Start by selecting the Classic Shell directory and it didn't work either. 

I performed the above just to see what could and couldn't be done. 

I just figured that the User Data would not be the same as the Classic Shell as well as the Registry Entries. 

I might play around with it a bit more since it's been a while since I had looked deeper into a Microsoft software (Formerly Microsoft Certified before I had retired from the Military). 

I've been developing apps and other Android related items for a while and had dealt with PC side very little for the past few years. 

I can report back any information if you would like. 


~Ibuprophen

**Comment by XenHat** [comment]
You should be able to export the registry keys manually and insert/type them back into the new registry location for the time being.

Sorry I haven't done any progress on that right now, there's been some pretty brutal heat warnings and I'm absolutely enable to work.

**Comment by ibuprophen1** [comment]
Don't I know it! It's 91° with a heat factor of 102° right now. 

I was actually beginning those steps too but, bouncing back and forth with 2 other developments for the Android. 

It is brutal outside and I've got to walk to the store... Oh My!!! :-D

**Comment by ibuprophen1** [comment]
@XenHat, I just wanted to let you know and i'm not sure if you're aware of this... 

After installing the Classic Start, the menu layout resets to its default state and then if I attempt to install the Classic Shell, the installer detects a newer version installed and exits.

This is fine but, if I uninstall the Classic Start and install the Classic Shell, the menu layout from the first start menu layout of the Classic Shell is there. 

The Classic Start installation is not truly an update/upgrade but, after its installation, the Classic Shell remnants still remains. You could say that they both see each other but, not everything is seen. 

I hope that I had explained this okay via text... :-) 

I've also been working on a type of batch file for registry and user entry backup/restore migration from the Classic Shell to the Classic Start. I'm not finished yet and I'm not sure if this is something your interested in as well. 

Thank you very much for your time, patience and understanding with this! :-) 


~Ibuprophen

**Comment by ibuprophen1** [comment]
@XenHat & @coddec... 

Just an FYI regarding a few remnants left by Classic Shell for a future cleanup on migration... 
___
**%LocalAppData%\ClassicShell**
**%AppData%\ClassicShell**
 ___
... they both have data/information that "Should" be copied from those directories and placed in the following directories before removal/deletion.
___
**%LocalAppData%\ClassicStart**
**%AppData%\ClassicStart**
 ___
Please let me know if you require clarification. :-) 


~Ibuprophen

**Comment by XenHat** [comment]
Yes, I've seen these when rebranding to Classic Start in https://github.com/passionate-coder/Classic-Start/pull/22. I simply didn't have the time to work on this yet. I will in a week or two. Sorry for the delay.

**Comment by ibuprophen1** [comment]
@XenHat, I'm not in a race or anything like that. I just wanted to keep you up to date with my personal findings, input, opinions, etc... :-) 

I actually had rethought my last comment regarding the 2 AppData directories and found that, instead of moving the contents and then deleting the 2 directories, it would be even better to just Rename those 2 "ClassicShell" directories to "ClassicStart" with the contents untouched. 

By just creating a "ClassicStart" directory would be redundant in itself because the content within the "ClassicShell" directory would be the same exact information as what the "ClassucStart" directory would have/include/create. 

I hope that I had stated this okay via text... :-) 

I've actually been looking at the applicable DLL file (and another possible one) for a personal fix to test out before pushing any form of commits review. 

What I would be looking to do is, simply put, for the installer to:

1) Look and see if the 2 ClassicShell directories within the Users AppData already existed. 

2a) If not, then create the ClassicStart directories and proceed from there. 

2b) if so, then rename the ClassicShell directory to ClassicStart (leaving the contents, if any, untouched) and then proceed from there. 

This is pretty much my Plan-A for my help and contribution to this development. 

I hope this looks good to you and the others My Friend! :-) 


~Ibuprophen

**Comment by ibuprophen1** [comment]
I just wanted to refer those to a recent comment I had made for those who may be interested on the progress of this specific topic. 

https://github.com/Open-Shell/Open-Shell-Menu/issues/64#issuecomment-412293525

Instead of posting a redundant copy and paste, i just provided a link to it. 

Thank you all very much for your time, patience and understanding with this! :-) 


~Ibuprophen

**Comment by ge0rdi** [comment]
Hi guys.

Latest [nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts) (4.4.129+) does support automatic `ClassicShell` data/settings import.

It will __copy__ all relevant files/keys after first `Open-Shell` installation.
Old data remains untouched, in case one decides to move back to `ClassicShell`.

Could you guys give it a try?

Prior to `Open-Shell` installation, I'd recommend to create backup of `ClassicShell` (so that you can restore if something goes wrong):
- `ClassicShell` XML backup (`Settings -> Backup -> Save to XML File`)
- Export `HKCU\IvoSoft` registry key
- Copy these folders somewhere:
  - `%APPDATA%\ClassicShell`
  - `%LOCALAPPDATA%\ClassicShell`
- Eventually copy content of `ClassicShell` folder in `Program Files`, especially if you are using custom skins

You can start installation of `Open-Shell` right over installed `ClassicShell`. In such case installer will have to close _Windows Explorer_, but it will start it again when installation finishes.

Or you can uninstall `ClassicShell` first (files and keys will remain). And then install `Open-Shell` from scratch.

**Comment by AveYo** [comment]
Works as intended, but:  
-it also needs to force an explorer restart after installation - it's needed to relaunch start menu, else you have to use the windows default menu to browse to Open-Shell - Open-Shell Menu Settings _(not that intuitive without a start/reload open-shell entry__
-debatable, but the initial configuration screen should be skipped if old settings were automatically imported

**Comment by ge0rdi** [comment]
> it's needed to relaunch start menu, else you have to use the windows default menu to browse to Open-Shell

That is weird. Because installer is supposed to run `StartMenu.exe` after installation finishes. So there should be no need to do it manually.

> debatable, but the initial configuration screen should be skipped if old settings were automatically imported

This is also weird, because the initial config screen should be displayed only if there are no settings stored in registry.
It shouldn't be displayed if settings were imported (or were present already).

**Comment by AveYo** [comment]
@ge0rdi, [Open-Shell setup [upgrade from ClassicShell] video on youtube](https://youtu.be/YD_MDAN3KGk)

Redone test, Open-Shell still can't close already running ClassicShell (a likely scenario).  
That's a huge issue for non tech-savy users as it leaves Explorer ui closed   
_(but an explorer.exe process still running)_.   

Easily fixed by simply end task the leftover explorer.exe process and the ClassicStartMenu.exe then continue setup.   

After doing that, can confirm for .129 that initial setup popup no longer shows when importing from ClassicShell.  

Maybe adjust setup code to kill those processes anyway and force explorer to reload?

_Just FYI,  I prefer to reload explorer via  `taskkill /im explorer.exe /f & taskkill /im sihost.exe /f`_

**Comment by XenHat** [comment]
Yeah, does the installer kill the old classic shell if settings are found? Seems like a few checks are failing

**Comment by ibuprophen1** [comment]
Closed for being addressed by the following... 

https://github.com/Open-Shell/Open-Shell-Menu/pull/74



~Ibuprophen
