### ISSUE TITLE
Less an issue, more a question

### ISSUE THREAD

**Issue by RitzyBusiness** [Open-Shell/Open-Shell-Menu#284]
Is it possible to make it so the open-shell menu opens up on mouse pointer rather then in the corner of the screen.  Kind of like the BB4Win (or Zero or all of its derivatives).  That would be an awesome feature, at least for me.

**Comment by Ibuprophen** [comment]
This is a very unique question, but unfortunately this is not possible since the software is fixed to the position of where the actual start menu is located. 

I'm not stating that this type of feature/behavior isn't possible per say since there may be some type of software somewhere on web that's designed to behave this way. It's just that this software was never designed to do this since it's predecessors first release. 

Sorry for the bad news, but thank you very much for asking. :-) 


~Ibuprophen
