### ISSUE TITLE
Windows Color Scheme Option

### ISSUE THREAD

**Issue by michaelleepow90** [Open-Shell/Open-Shell-Menu#322]
It would be neat if there was an option to create Windows Color Schemes, like what Windows 95 had.

![Slate (Windows Color Scheme)](https://user-images.githubusercontent.com/25166581/75099052-acf6bd80-5569-11ea-9a65-0aea6cdf3d42.gif)

![win95schemes](https://user-images.githubusercontent.com/25166581/75099097-2bebf600-556a-11ea-9815-4fee04b00f7c.png)

**Comment by xcasxcursex** [comment]
Sadly, those don't work properly any more. The colours are stored in the registry at `HKEY_CURRENT_USER\Control Panel\Colors` and you can feel free to tinker with them in there. But be warned: Take a backup (File... Export) of that key before you start because it will break things all over the place and you'll likely wish you never changed it.

This project may interest you, for changing the colours that actually do still work: https://github.com/Raymai97/AccentPaletteTool/

In fact, since I've seen people go down this route before, and come back later asking what the defaults are.... I've backed it up for you. But take my word for it - or don't, and just search the web and everyone agrees - this doesn't work like you want it to. It's intentional. MS want people using UWP.... because...they hate us all, or something.
[default colors.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/4703047/default.colors.txt)

**Comment by michaelleepow90** [comment]
Cool, it's ok, just checking. Thanks for the link.
