### ISSUE TITLE
"Start Menu (Windows)" link no longer works

### ISSUE THREAD

**Issue by coffent** [Open-Shell/Open-Shell-Menu#329]
The "Start Menu (Windows)" link (normally the first link listed with Open Shell Menu) triggers, or should trigger, "StartMenu.exe -togglenew".  It used to cause the standard Windows 10 start menu to be displayed.  Lately I find it doesn't:  When I click on it the Open Shell menu disappears and there's a brief flash of an hourglass, but that's it.  Have others experienced this problem?

**Version:**
 - Open-Shell: [4.4.142]
 - OS: [Windows 10]

**Comment by ge0rdi** [comment]
Does the same happen when you'll run `"C:\Program Files\Open-Shell\StartMenu.exe" -togglenew` manually from command line?

Try to press `Shift+WinKey`.
Does it show original Windows start menu?

**Comment by coffent** [comment]
Same thing happens (quick hourglass only) either running "StartMenu.exe -togglenew" from the command prompt or pressing shift+WinKey.  Also, running StartMenu.exe (without the -togglenew) does *not* bring up the Open-Shell menu - that occurs only by clicking the Windows icon.

**Comment by reffu42** [comment]
I have the same issue after windows update installed "KB4537572 Cumulative Update for .NET Framework 3.5 and 4.8 for Windows 10 Version 1903". On restart, clicking the windows start button now opens the windows start menu, no matter what options I choose in open-shell. The windows key still opens open-shell and if I enable the open-shell start button, it works but is overlaid on top of the existing windows start button so I have to click around the bottom edge of the taskbar to open open-shell, rather than the windows start menu.

**Comment by reffu42** [comment]
Huh, may have been the restart, but installing "KB4535996 - Cumulative Updated for Windows 10 Version 1909", and restarting seems to have fixed it for me.

**Comment by coffent** [comment]
I've run both the -572 and the -996 updates and still have the same problem.  It seems to be the exact opposite of reffu42's problem.  Clicking the Windows start button or pressing the Windows key both open the Open-Shell menu as expected.  But once open, clicking Start Menu (Windows), which is supposed to bring up the original Windows menu, does nothing.

**Comment by coffent** [comment]
I found the source of the problem - it was a problem with Windows.  I did an "in-place repair" of Windows and now Open-Shell behaves correctly.
