### ISSUE TITLE
Fix the right-hand menu spacing in the Start Menu to more closely match Windows 7

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#354]
In the Windows 7-style menu, the items in the right-hand menu are too closely spaced together. This has been the case since the style was introduced, and I would love to see an improvement in that aspect.

**Comment by CTVCAM8** [comment]
I believe Ivo the original developer, made it that way on purpose. When there are no static icons like in XP classic 2 type menus,
why waste the vertical space when a lot of users love to load up the second column with a ton of personal shortcuts.
Also, the selector buttons Ivo used in the Windows Aero type menus don't have the extra white surrounding edge as in the original Windows 7 start menu, 
that add 2 pixels vertical height.

The only way right now is either download a user modified .skin7 from the Classic Shell forum site, or modify the "Main2_text_padding" in skin dll file with Resource Hacker:

http://www.angusj.com/resourcehacker/

Make a copy of the original skin you want to modify and put on your desktop. Rename it to some other name. 
It's best to not modify the skin file in the Skins folder as it may get corrupt.

Look for the below text in the .skin7 file

Main2_text_padding=1,7,8,7,100% 

as well as 

[SMALL_ICONS]
Main_large_icons=0
Main_arrow_padding=7,9,100%
Main_split_arrow_padding=9,9,100%
Main2_text_padding=1,3,8,4,100%

This second "Main2_text_padding=1,3,8,4,100% " only turns on when Small icons option is picked in the skin options. 
There are no icons anyway in 7 style 2nd column, but it makes both columns match approximate size.

The first and third numbers are left and right invisible horizontal padding inside the button.
The second and fourth numbers are for the top and bottom vertical padding inside the button.

After increasing the numbers you want to say "Main2_text_padding=1,9,8,9,100%", click the "Complile Script" button, and save it to the skin on desktop.
In order to see the skin file on the desktop with the save window, change the dropdown list to "All files".
After it is replaced on desktop, copy that file and put it in the Skins folder. You might need to be an administrator to do that. 
It should show up in the Skin drop-down list. 

For better explanations on this subject here are a few of older Classic Shell links that I Googled:

http://www.classicshell.net/forum/viewtopic.php?f=7&t=4853

http://www.classicshell.net/forum/viewtopic.php?f=13&t=2702

http://classicshell.net/forum/viewtopic.php?f=7&t=1139

http://www.classicshell.net/forum/viewtopic.php?f=7&t=7270

http://www.classicshell.net/forum/viewtopic.php?f=13&t=3144

**Comment by bonzibudd** [comment]
Thank you so much! I have been looking for a solution for this for a while, now I know where to look.
