### ISSUE TITLE
Change the functionality of searching for commands (regedit, cmd, calc, winver, etc.) so they don't appear as results unless they are typed exactly.

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#359]
The current behavior is somewhat annoying since I sometimes press enter on an unwanted result. I think that most people would prefer this, however I would love to hear what others think of the behavior.

**Comment by NebelNidas** [comment]
> The current behavior is somewhat annoying since I sometimes press enter on an unwanted result.

That usually only happens the first time you open a program. I for example have a program called "Glass CMD" on my computer. The first time I searched "cm" with a freshly installed Open Shell, it shows "cmd.exe" as first result. OK, not what I wanted, but the next time I search "cm", Open Shell knows I opened "Class CMD" more often than "cmd.exe", and thus the first result is "Glass CMD"! So because Open Shell remembers which programs I open more frequently, it doesn't really annoy me and I think we should leave this as is.

**Comment by bonzibudd** [comment]
I'm closing this. It looks like my request is configurable, and I am 99% sure this is synonymous with the "match parts of words" option in the Search box tab.

**Comment by NebelNidas** [comment]
Topic picked up again in issue #463.

**Comment by bonzibudd** [comment]
I’ll keep this one closed since there seems to be a larger discussion on the new one. The toggle for “Match parts of words” seems to only partially accomplish this, unlike what I thought previously.

**Comment by NebelNidas** [comment]
Yep, I just referenced the new discussion here for meta purposes. 😁

**Comment by XenHat** [comment]
My apologies. Despite searching for an existing issue, I failed to find it.
