### ISSUE TITLE
trouble with new name - Possible name copyright issue

### ISSUE THREAD

**Issue by Aokromes** [Open-Shell/Open-Shell-Menu#36]
I have found this app, maybe they will force to change name.
http://www.classicstartmenu.com/

Gitter:
https://gitter.im/passionate-coder/Branding

**Comment by ibuprophen1** [comment]
I'm familiar with this and the developer for that software "Dennis Nazarenko" has several different websites for several different variants of the Start Menu software that's very limited and not as versatile as the Classic Start software. 

Also keep in mind, those are, what I call, "Pay for Pro" software. 

The Classic Start is much more versatile and is totally free. 


~Ibuprophen

**Comment by coddec** [comment]
> I have found this app, maybe they will force to change name.
> http://www.classicstartmenu.com/

@Aokromes 
Thanks for the info!
I guess This is something we need to be aware of, but I'm not familiar with relevant law. We need a lawyer here 🤣🤣🤣 
Anyone know if we have to take any action to cope with this or is doesn't matter??

@ibuprophen1 
I guess Aokromes is talking about the copyright and other ™ ® © stuff 😂
But thanks for pointing out Pay for Pro and difference of software, good to know 😉 👍

**Comment by ibuprophen1** [comment]
@coddec, I don't believe that there's anything legal that can be done about this for 2 reasons. 

1) That software has been out for at least 4 years (I believe longer) shortly after Windows 8 was released. 

2) This software is named "Classic Start" and that one is named "Classic Start Menu". 

Those look like a legal technicality between the two names as well as the length in which they both have been released. 

This is what I've found by doing a quick research into Title 17 USC § 501 regarding the Laws Governing Copyright Infringement. 

Maybe someone else here can clarify/correct myself for this... :-) 


~Ibuprophen

**Comment by coddec** [comment]
@ibuprophen1 
Thanks for the info! & Speedy research 😄 
👍 👍 👍

**Comment by ibuprophen1** [comment]
It was my pleasure to have helped... 😇 

I'm quite resourceful and am also very familiar with various legal aspects in research. 

FYI... I do have an "Esquire" at the end of my name... LOL! 

Let's say that I'm a "Jack of all trades and master of none" LMAO 😵 

I use my powers for good and have never turned to the Dark Side... 😱 


~Ibuprophen

**Comment by coddec** [comment]
@ibuprophen1 
You are really resourceful! 👍👍👍 😄 
The world needs both "Jack of all trades and master of none" & "Master of 1" 😉 
> I use my powers for good and have never turned to the Dark Side... 😱
Glad to know that! Hope all of the people will use powers for good 😉 😉 sadly it's not true 😞

**Comment by Aokromes** [comment]
the problem here is the names are to similar, and the target of the software the same....

**Comment by Aokromes** [comment]
I suggested classic shell reborn :) on that way people trying to find for classic shell will find new name.

**Comment by bolera** [comment]
why not ...

**Comment by coddec** [comment]
Ivo wants keep the `Classic Shell` and hold the rights.
That's the reason to change the name at first place.
https://github.com/coddec/Classic-Shell/issues/13

@XenHat @ge0rdi 
Guys we might have some issues here.
I really don't want you to waste your re-branding effort too...

**Comment by Aokromes** [comment]
Classic Launcher?

**Comment by Quentinix** [comment]
Classic shell remains a good solution for the reputation gained over the years.

**Comment by bolera** [comment]
I wasn't aware of this other discussion. Did you ask Ivo if "Classic Shell" with an addition like "reborn" is an option? If you continue with "Classic Start" there's a real clash with "Classic Start Menu". If he sues you you **might** win the case - but it takes resources. I would avoid this if I were you. Also, it lists both of you very near in a search engine and he might actually draw attention from **you** (people may mistake his effort for yours and install **his** program). What about just "Shell Reborn"? Reminds of Bash (Bourn again shell).

**Comment by ge0rdi** [comment]
I personally think there is no need to panic nor rush anything.
I'd stay with `Start Menu` as we've already agreed.

If they guy with `Classic Start Menu` decides to do some action, we could reconsider.
We can rename later if really necessary.
The worst thing that can happen is that the guy manages to convince Github to delete this repo.
But since we have the code (it cannot be really deleted), we can easily _reborn_.

For now I'd just suggest to have product name defined at one place, so that we can eventually easily change it.

Though if you guys want to change the name, I don't really care.

**Comment by coddec** [comment]
@bolera 
Thanks for the suggestions.
I too don't want us get in trouble.
Ivo doesn't want us use his names too.

@ge0rdi 
I kinda thinking the same. Just don't want use get into trouble.
The name variable suggestion is good one!

**Comment by ibuprophen1** [comment]
Okay @coddec... 

I did a bit more digging into this and, from what I had located, it looks like good news for you! 

I had a few windows/browser tabs open, on my PC, to the following links:

1) To the following US Government's "Trademark Electronic Search System (TESS)". 

http://tmsearch.uspto.gov

2) To the following website in question. 

http://classicstartmenu.com/

3) To the following company website "OrdinarySoft" that owns the ClassicStartMenu.com website (as seen on the bottom of that link). 

http://www.ordinarysoft.com/
 
4) The following "How to Do a Trademark Search Before Choosing a Business or Product Name" link that a "Legal Eagle" friend of mine referred me to regarding this that has very valuable information within it. 

https://www.nolo.com/legal-encyclopedia/how-do-trademark-search-29741.html

After performing a handful of searches (using variable keywords because of the "Metadata" system that the TESS uses). I'm familiar with this type of system as a retired/former Government employee myself. 

I found out the following important information regarding this, potential and unnecessary panic attack that is being fueled a bit and you, @coddec, seems to be calm about it at the moment. 

Of course the company name "OrdinarySoft" is registered but, NOT the name Classic Start Menu nor ClassicStartMenu as these two phrases are "descriptive" in nature and NOT "specific". 

With that stated, ONLY the "ClassicStartMenu.com" is registered as a whole. 

Now If you were to look at the "http://www.ordinarysoft.com/" website, none of the software is named "Classic Start Menu" nor "ClassicStartMenu". 

The only words/names "Classic Start Menu" or "ClassicStartMenu" that's being used is ONLY the URL and NOT the software itself. 

To add... the word/name that is slightly encompassed in any registration is "ClassicStartMenu.exe" and is specifically linked to "ClassicShell" and our good friend "Ivo Beltchev". 

I hope that I had explained this okay via text... :-) 

Please let me know if I'm wrong with one or more of the above information provided. I'm not perfect and, no matter the experience, i can be wrong. 

Thank you very much for your time, patience and understanding with this! :-) 



~Ibuprophen

**Comment by bolera** [comment]
This is not correct.
Go to http://classicstartmenu.com/ and **read it**! The application is called "Classic Start Menu" and the setup program to it is either. http://www.classicstartmenu.com/ClassicStartMenu.exe

**Comment by bolera** [comment]
_To add... the word/name that is slightly encompassed in any registration is "ClassicStartMenu.exe" and is specifically linked to "ClassicShell" and our good friend "Ivo Beltchev"._
This makes no sense. Why would "ClassicStartMenu" be "linked" to "Classic Shell"?

**Comment by bolera** [comment]
Here's another domain of his: http://www.sprigsoft.com/ It lists the program as "Windows 7 Classic Start Menu".
Don't get me wrong. You may very well win a law suit because the name cannot be trademarked because parts of it are "descriptive". However, if you combine those parts you have a different case. And you never know before what a court is going to rule. 
It doesn't matter so much that there is no trademark for "Classic Start Menu" as software filed. Depending on the country you can just be filed for the similarity because you want to "prey" on an already existing, established and widely known (according to Google and the many websites) program name.
Ibuprophen may still be right in his assessment. But you cannot be sure. I would either change the name or contact a lawyer. Maybe contact FSF, they may provcide advice and a free lawyer.

**Comment by david-rahrer** [comment]
As I understand it, there are a few things to consider here. FYI, this is US specific.

1. The maker of Classic Start Menu does not need to have registered the name anywhere to have rights to it. It does make it easier in court but the key is who had "first use in commerce."

1. The primary consideration in such matters is whether one can make a case for "confusion in the marketplace." The names could be identical and still not cause confusion and therefore not be infringing if the product or service is distinctly different (Delta Airlines vs Delta faucets).  In this case, since both products have the same basic purpose, the fact that the names are so close could very well be an issue.

1. While domain name registrations can be affected by the outcome of a legal decision, who registered what domain does not confer any extra rights in a copyright or trademark case. 

1. The term "Start Menu" may have first been used by Microsoft in Windows 95 (I don't really know) but they don't seem to have ever registered it. I don't know if that makes any difference to this discussion.

I am not an attorney, but I had to research this stuff for my own trademark issues years ago. The bottom line is that anyone can sue for anything, and even a brief engagement would be a mess, especially for an unfunded project. Also, I do not know but don't believe that point 1 above is affected by whether or not one charges for the product.

It should also be noted that, since this has now been discussed openly and publicly, it could not be claimed that the issue was unknown. It doesn't change the legal argument, but might be taken as conscious disregard for the rights of the other party, i.e. you were aware there may be an issue and went forward anyway.

Full disclosure, I am the person who suggested "Start Again" as a possible new name in the earlier discussion.

**Comment by ibuprophen1** [comment]
OH MY!!! 😨

Please don't think that my information is specific to misleading and such. I'm REALLY NOT trying to contradict, condescend, argue, debate, etc... 

I'm only trying to provide some input regarding this whole mess and am in no way outright lying about this either. 

Everyone is making a good point but, unlike myself, to state that I (or anyone else) is completely wrong without providing any legal reference nor prescience doesn't make it "legally" correct. 

I believe that this form of debate is really going in circles and isn't getting anywhere at all. 

I believe that the best advice that I can provide @coddec is to ask an Attorney who specializes in "Patent/Copyright Law". 

I will no longer comment on this specific issue and I truly hope that this works out for the best with @coddec. 

I don't want to see this project end in any way and I'll do what I can to provide what help I can for making/keeping this project as great as it ever has been. 

Peace and Love! 
Peace and Love! 
~Ringo Starr 


~Ibuprophen

**Comment by david-rahrer** [comment]
> I believe that the best advice that I can provide @coddec is to ask an Attorney who specializes in "Patent/Copyright Law".

Agreed.

**Comment by bolera** [comment]
> I believe that the best advice that I can provide @coddec is to ask an Attorney who specializes in "Patent/Copyright Law".

That's why I suggested to contact FSF. The project may get free legal advice from them.

**Comment by Quentinix** [comment]
it's possible @bolera ?

**Comment by XenHat** [comment]
We already did a poll for the new name, we could do a new one.
Since this is an issue tracker and not a forum, I would ask everyone to move the conversation to Gitter (you can sign in with github): https://gitter.im/passionate-coder/Branding

**Comment by XenHat** [comment]
@ibuprophen1 & @bolera Both your insight and help is extremely helpful. I would appreciate if you could continue to help us in your best ability. I don't think anyone is trying to "win" here, nor it is necessary.

**Comment by Nodens-** [comment]
> The maker of Classic Start Menu does not need to have registered the name anywhere to have rights to it. It does make it easier in court but the key is who had "first use in commerce."

This is also true for the EU as I had experience with branding conflict before over here. It doesn't matter if the software is paid or free. As long as the functionality is similar and the name is in use for longer (something that can easily be proven for software), it stands in court. That much I know for sure as a company I worked with had to settle for damages against the software with the original name for this particular reason and it was quite costly.

The best advice given here already is to contact the FSF for this as there are no funds for proper legal advice.
 Although in my opinion the best course of action is just go with a different name and avoid the potential clash altogether.

**Comment by Rainmaker52** [comment]
Why don't you just ask the holder of the name for permission?

Just email ordinary soft, tell them you have this open source project, tell them you accidentally renamed it to a name similar to his registered name, and ask if they are ok with it.

Once you have their response in writing (email) there's no problem anymore.

Only if they object to you actually using the name, this might be a problem and warrant a new new name.

If you're up for it, you could take it to court. This is not only a matter of who was first. There's also a rule preventing you from registering common words. I would think "start menu" is such a common word. But at that point, you'd have to rely on a judge to agree. Which is probably a little more risk then you'd like to take over a name.

Disclaimer: not a lawyer. Not even a US citizen. But do know a little about software patents

**Comment by yereverluvinunclebert** [comment]
"Start Menu Reborn" is nice and simple. It is catchy. It states what the functionality is and won't annoy anyone. Of course the accidentally-conflicting original choice is unfortunate but that's the way it is. You can't have conflicts as it simply confuses and does not allow differentiation between the different offerings. "Start Menu Reborn" is not only catchy but it gives the product a feeling of having a regenerative and productive quality.

**Comment by ibuprophen1** [comment]
@XenHat had opened up a Gitter link specifically for name suggestions. 

If nobody is there, you can make your suggestions and one of the developers will see it when they have a moment to look. 


~Ibuprophen

**Comment by bolera** [comment]
Congrats on the new name, looks good!
