### ISSUE TITLE
Icons / apps not showing up in start menu

### ISSUE THREAD

**Issue by ylluminate** [Open-Shell/Open-Shell-Menu#363]
In the most recent release of Open-Shell I'm seeing missing app icons on a number of installations and I haven't been able to isolate a rhyme or reason for it yet:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/DOuAR4XA/openshell_menu.png)

**Comment by NebelNidas** [comment]
Did you perhaps append the wrong screenshot? Because judging from my observations, everything looks as it should. Anyways, I also have an issue with app icons, specifically the one of the newly released Windows Terminal:
![image](https://user-images.githubusercontent.com/48808497/83496746-d18ff900-a4b9-11ea-80fa-7f76b555ae83.png)
This only happens when having set "Invert Metro icon color" to true, with it set to false it looks like it should:
![image](https://user-images.githubusercontent.com/48808497/83496879-00a66a80-a4ba-11ea-9eb4-5b74ac87d257.png)

Is this also your problem, @ylluminate, or did you mean something else?

**Comment by NebelNidas** [comment]
Do you mean the frequently used programs not showing up? To solve that, go to _Windows Settings -> Privacy -> General_ and turn on _Allow Windows to track app launches  to improve start and search results_.

**Comment by blackcrack** [comment]
also can you setting up the entry's of this .. the links comes up by often open frequently Programs up to 10 or so many how you have setting up..
