### ISSUE TITLE
This is not necessarily a "bug" report

### ISSUE THREAD

**Issue by furryface47** [Open-Shell/Open-Shell-Menu#369]
SOMETHING broke Open Shell. It was working fine then all of a sudden it would flash up the Open Shell start menu and then it will disappear in milliseconds and display the hated Metro menu. I tried uninstalling the latest updates but one won't uninstall. Help!!!

**Comment by ge0rdi** [comment]
What OS/Open-Shell do you have?

Please, create log using [How to obtain advanced Open Shell Menu log](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log) wiki page and attach it here.

**Comment by NebelNidas** [comment]
Yeah, some further clarification would be neat.
>all of a sudden it would flash up the Open Shell start menu

What do you mean with "flashed up"? Did it crash? Sounds so, because in the following you state that afterwards it only showed the default Win10 menu. But have you tried restarting Open Shell? The easiest way to do so would be to open its settings window.
>I tried uninstalling the latest updates but one won't uninstall

So you attempted to uninstall Open Shell using the default uninstaller, accessed from Windows' Applications Settings Page, I assume. But in which way did it fail? What error message did appear? Some screenshots would make it much easier to troubleshoot. 😉
