### ISSUE TITLE
Update Chocolatey package

### ISSUE THREAD

**Issue by dertuxmalwieder** [Open-Shell/Open-Shell-Menu#37]
As it stands, there is a [Chocolatey package](https://chocolatey.org/packages/classic-shell) with the la(te)st version of Classic Shell. As I'm certain that the creator must be somewhere around here, I'd like to suggest to update it as well.

**Comment by ibuprophen1** [comment]
This was a very good catch @dertuxmalwieder! 

@coddec and @XenHat, the following Github location (provided on that website) is where this is located and provides the "Classic Shell" as part of their package. 

https://github.com/chocolatey/chocolatey-coreteampackages

Did those developers get permission for including the Classic Shell development within their packages? 

Just curious... :-) 


~Ibuprophen

**Comment by ibuprophen1** [comment]
I would just like to quickly add @dertuxmalwieder... 

Please correct me if I'm wrong @coddec and @XenHat. 

I would recommend (as I always do for various software and such) if there's a package deal with various developments within it, from any outside developers, I always get them from the source for up to date releases as well as developer support and guidance. Those developers know the software better than anyone else. 

For example, one of my Android Developments called "The SELinux Switch" is also being provided by others (within various locations on the Internet). 

I do get support questions regarding the Switch App from those who had obtained it from a third party source. I always respond by telling them to uninstall it and install it from the developers source that ends up (most of the time) resolving whichever issue they are experiencing. 

I truly hope that you and others understand what I'm explaining (the long way LOL!). 

Always get what is needed from the developer and, Importantly, unless otherwise stated by the developer, don't obtain anything from a 3rd party because of the potential to do more harm than good. 

-----fin-----


~Ibuprophen

**Comment by ibuprophen1** [comment]
It looks like this issue has been (or still being) addressed... 

It seems, to me, like this issue should be closed. 


~Ibuprophen
