### ISSUE TITLE
Open Shell installer can't replace Classic Shell after Win10 Upgrade.

### ISSUE THREAD

**Issue by DLLarson** [Open-Shell/Open-Shell-Menu#371]
I upgraded a Win8.1 Pro system which was using Classic Shell 4.1.0 to Windows 10 Pro. When the upgrade was finished Win10 says it uninstalled ClassicShell because it's not supported by Win10. However the app is still listed in the programs install list of windows.

When I attempt to install the latest OpenShell (circa 6/6/2020) I get the following errors show in the following screenshots:

![OpenShellInstallError-1-20200606](https://user-images.githubusercontent.com/175455/83946676-f1842d00-a7d7-11ea-9ed6-ca20e863cee7.png)

and

![OpenShellInstallError-2-20200606](https://user-images.githubusercontent.com/175455/83946681-f6e17780-a7d7-11ea-9144-eb0fc65219a7.png)

I tried finding the requested msi both on the machine and on the 'net but could not locate a version. Plus even the relevant (4.1.0) version of classic shell's exe installer won't even run in Win10.

I'm totally hosed here. What can I do to manually remove the prior knowledge of classic shell so I can install Open Shell?

Help!
-Dale

**Comment by NebelNidas** [comment]
What a coincidence, I also got this error yesterday with LibreOffice when downgrading from Win10 2004 to 1909. Basically, Windows removed the .msi file necessary for installing and uninstalling the application, but didn't actually uninstall the program. And because MSI packages can't be installed if an older version is present, the new installer will attempt to uninstall the old version of Classic Shell with the corresponding old uninstaller, which isn't present leading to a situation where you can't really do anything. Typical Windows 10 in all of its glory...

So, in order to get rid of the old version, you will need its MSI file (judging from your screenshot it's Classic Shell 4.1.0 x64, which is terribly outdated by the way). I hope you still have it lying around somewhere, if not you can try getting it from the internet ([FileHippo](https://filehippo.com/download_classic_shell/4.1.0.0.0/post_download/) for example has it archived, but I don't know if it's the x64 version). Then, using the first dialogue you posted a screenshot of above, browse to it  and click OK, then it should successfully uninstall the old Classic Shell and install the latest and greatest Open Shell.

**Comment by DLLarson** [comment]
Thanks for the reply.

After a fruitless search and failed attempts at reconstruction of the missing MSI file I took the desperate approach of deleting all registry keys having "Classic Shell" in them. 

I say desperate because I sense that Classic Shell could have hooks all over the place. On the other hand the Windows 10 upgrade process *did* say it had uninstalled Classic Shell as part of the upgrade so I was counting on that basically assuming that the only leftover data was for the install itself.

Lo and behold it worked! 

After removing the registry data I could install "Open Shell" with no issues. What a relief that was!

I'm closing the issue with this post.
-Dale

**Comment by NebelNidas** [comment]
Yeah, you unfortunately need the **exact** same MSI file you installed the program with, otherwise it won't work... 😕
Cleaning up the registry manually is the last option one has, but isn't very good since you leave a lot of clutter behind. Therefore you normally should install Classic Shell again afterwards and then uninstall it correctly with the bundled uninstaller, in order to truly remove everything.
However. if you don't care for a few left over registry keys and files, @DLLarson, I would now leave your system as is since it's not worth setting everything up again for these trivial issues.
