### ISSUE TITLE
Issue with the "White Sub-menus" option

### ISSUE THREAD

**Issue by radzo73** [Open-Shell/Open-Shell-Menu#384]
**Describe the bug**
When "White Sub-Menus is disabled, sub-menus use a light gray color, instead of my selected System theme (In my case, it would be Dark) 

**To Reproduce**
1: Turn off "White Sub-Menus" while using a theme based on Windows Aero
2: Your sub-menus are gray :c

**Expected behavior**
I expected them to be dark, to match with my System theme

**Screenshots**
With "White Sub-menus" enabled:
![image](https://user-images.githubusercontent.com/26673668/85213862-09a89000-b332-11ea-8833-efa4d9dc901b.png)

With "White Sub-menus" *disabled*:
![image](https://user-images.githubusercontent.com/26673668/85213851-e4b41d00-b331-11ea-97c8-fd4ff63fa8ad.png)

**Version:**
 - Open Shell 4.4.142
 - Windows 10.0.18363.900

**Etcetera**
Why can't we change the color of the inside menu from white to a different color?

**Comment by CTVCAM8** [comment]
Hello @radzo73

The Aero skin was made to look like the Windows 7 start menu, 
years before Dark mode code came out in Windows 10

When the White sub-menus option is enabled, "Submenu_background=#FFFFFF" (white color) text in the skin file overrides
the default grey System Color in the registry, which I believe is:

[HKEY_CURRENT_USER\Control Panel\Colors]
"Menu"="240 240 240" 

Unless the coders come up with some kind of dark mode submenu override option for all skins,
you can pick a different skin, or download a modified user skin from Classic Shell forum, 
or learn to edit the skin:

https://coddec.github.io/Classic-Shell/www.classicshell.net/tutorials/skintutorial.html

Adding a darker grey "Submenu_background=#2B2B2B" in the skin file would be easy. 
The hard part is changing the text and images to be able to see the submenu text. :)

![Aero dark grey submenu](https://user-images.githubusercontent.com/44127216/85219704-e9d99200-b35a-11ea-9423-ccaa7168be65.png)


Also, that submenu has no image in the skin. 
It is drawn opaque from Windows with a dark grey border.
it might be better to make your own submenu bitmap image if transparency is required.

Quote [Why can't we change the color of the inside menu from white to a different color?]
Mostly because the white color is on the menu bitmaps as well as they don't have a color mask in the white locations. 

In case you are interested, here is a link to the Windows 8 Dark skin:

http://classicshell.net/forum/viewtopic.php?f=17&t=8553

I turned all the white menus to dark grey.

**Comment by CTVCAM8** [comment]
Simple text mod (no modified bitmap images) that can be added to Windows Aero skin

To get just the outside submenu to a dark grey color like in the above picture,
copy the "Windows Aero.skin7" from the "Skins" folder to the desktop.
Open it up with ResourceHacker.
Open up the SKIN 1 folder that has the text script file. 
Add the below chunk of text to the very bottom of the script file:




OPTION DARK_SUBMENUS=Dark sub-menus,0,WHITE_SUBMENUS,0
[DARK_SUBMENUS]
Submenu_background=#2B2B2B
Submenu_separator=11
Submenu_separator_slices_X=15,100,15
Submenu_text_color=#FFFFFF,#FFFFFF,#7F7F7F,#7F7F7F
Submenu_arrow_color=#FFFFFF,#FFFFFF
Submenu_pager_mask=#400000
Submenu_pager_tint1=#000000
Submenu_selection=10
Submenu_selection_slices_X=4,63,4
Submenu_selection_slices_Y=4,20,4
Submenu_split_selection=16
Submenu_split_selection_slices_X=4,63,4,0,16,4
Submenu_split_selection_slices_Y=4,20,4
Submenu_new_selection=10
Submenu_new_selection_mask=#FF0000
Submenu_new_selection_tint1=#1890EF
Submenu_new_selection_slices_X=4,63,4
Submenu_new_selection_slices_Y=4,20,4
;below text blends selectors into submenu getting rid of blue sheen look.
;to enable remove the ; from below lines
;Submenu_selection_mask=#500000
;Submenu_selection_tint1=#2B2B1B
;Submenu_split_selection_mask=#500000
;Submenu_split_selection_tint1=#2B2B1B




Now, click the "Compile Script" button at the top and save the .skin7 file with a different name. 
Copy that modified file and paste in the Skins folder of Open-Shell.
To enable the dark option, enable the White sub-menu box first, then enable the Dark sub-menu box.

**Comment by radzo73** [comment]
Thanks for the help!
Before I close the issue, how would I change the color of the main menu?

**Comment by CTVCAM8** [comment]
The inside programs tree area is the same similar text to add that is just renamed to match the location:

Programs_background=#2B2B2B
Programs_selection=10
Programs_selection_slices_X=4,63,4
Programs_selection_slices_Y=4,20,4
;Programs_selection_mask=#500000
;Programs_selection_tint1=#2B2B1B
Programs_new_selection=10
Programs_new_selection_mask=#FF0000
Programs_new_selection_tint1=#1890EF
Programs_new_selection_slices_X=4,63,4
Programs_new_selection_slices_Y=4,20,4
Programs_text_color=#FFFFFF,#FFFFFF,#7F7F7F,#7F7F7F


The hardest part is where there is white on the three main menu bitmaps, etc. 
It might be a good idea to put the modded skin on the back burner (as I have done),
until you have a lot of time to play with it.

Main_bitmap=1
Main_bitmap_search=8
Main_bitmap_jump=13 
Search_background=23
Programs_icon=7 and 30

They would have to be edited in an image editor (free "Pixelformer" due to 32-bit bitmaps) to change the white areas to whatever grey darkness you want.
Also, Main_pager and Main_pager_arrows (2 sizes) images to better match a darker menu.
There is so much text to change too.
It would need the same text changes for text, arrow colors in the main, main2, list sections. 
Part of the shutdown section and search section. Maybe more!   

You could make extra bitmap images, modify them and add them as new identity numbers, and put all the modded text under the Dark sub-menu section, so the skin can have the original white look or the dark look when enabled. Up to you.
It probably will take a couple of days for you to work it all out. 
Good luck :)

**Comment by CTVCAM8** [comment]
Hi @radzo73

If you managed to add dark menus to your skin, then great.
 
If you don't have the time to figure it all out, 
I made just an all dark Windows Aero skin 7 style(no white menus option):

http://classicshell.net/forum/viewtopic.php?f=17&p=36401&sid=dca2d3ff5a5a51b017654dc69f14b0e7#p36401

It is very similar to the Windows 8 Dark menu skin in the same post.


If you do use the skin, you will notice the search box flashes a bright rectangle for a split second. 
I've never been able to figure out why. I'm sure it has something to do with glass color opacity timing.

In Win10, the program's scrollbar is always light-colored. 
I didn't attempt to add scrollbar images and text in the skin, 
for Open/Classic shell program won't show it anymore.

You can use it as a base skin to modify the colors to your taste. :)
Your screenshots look like you are using 120dpi display settings.
I added a 120dpi option that makes arrows, user picture, etc bigger. :)
