### ISSUE TITLE
Add an option to add a button as a .ICO, or some other method to automatically adjust for DPI

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#395]
This would be a nice option to have as it would allow for a single custom button to be used at multiple DPIs without manual resizing.

**Comment by CTVCAM8** [comment]
If you are referring to selector buttons on the start menu, 
selectors shrink/expand in height/width automatically for DPI, font, text, and program icon sizes.

My observations

A simple opaque selector is drawn in code.

A semi-transparent selector bitmap image with a simple 1-pixel border looks pretty much the same at 100% size as 150% size.

In most cases even a fully textured selector bitmap will look ok, for the corners don't distort because 
they are protected from changing size.

If there is a gradient inside the selector when stretched to fit 150% size the selector will show noticeable thick pixel lines. 
If the selector image is made with the middle area bigger with more pixels in the gradient, 
it will look a lot smoother when displayed using just one selector button image for all menu sizes. 

Using a different technique Ivo, the original developer added noise to the Windows 7 Aero selector button image to smoothen out the lines so it looks acceptable at high DPI. There will always be a little line distortion because in general, any image looks best when displayed at the exact size it was made for. With selector buttons that are continually changing size in a start menu, it's inevitable they will never look perfect all the time.

About the only time, I can think of having multiple accurate sizes of selector buttons
is when there are round corners on the button. 
At 150% size, the corners will look out of proportion (too small) to the rest of the button
showing a smaller radius than it should. Most users may not even notice this difference.

Maybe you want images to use Vector graphics?  :)

**Comment by bonzibudd** [comment]
@CTVCAM8 I appreciate your input, but I was actually referring to the Start button on the Taskbar. I definitely should have been more clear haha. As for the selection buttons, I see what you mean about the issues that the rounded corners and gradients pose at a higher DPI.

**Comment by CTVCAM8** [comment]
Yeah, The Start button can look pretty fuzzy with the resizing feature. :)
I wonder if it could use bicubic resizing, or maybe it already does?

Correct me if I wrong, but doesn't a .ICO have multiple images that would have to be made.
There would have to be additional images for the small taskbar to fit as well,
and anything in between those sizes will get resized by Windows and look fuzzy again. :(

Maybe the future is Scalable Vector Graphics used everywhere including the Start button?

**Comment by blackcrack** [comment]
nonsense.. how it is now it is well so far.. hey, if you have so "nice"  notion or Idea's, could you maby help at Reactos https://github.com/reactos/reactos a WinNT replica now developing at direction XP.. that's where you should start, at the base.. where something, a WinNT system is developed.. direcktly integrate fresh ideas..

**Comment by CTVCAM8** [comment]
Hi @blackcrack

[nonsense]
Hey, I don't see anything wrong with dreaming up a solution even if it never happens.
It might trigger a coder to innovate code.  :)

From what I understand, open-source platforms are made to share info for all to see and use to make every software better. 

Open-Shell and Classic Shell are just programs for operating systems that have been released to the general public.
For me, they work 99.99% perfectly.   
We have been encouraged, even if we don't have the coding know-how to help out with possible solutions and features to be included in the Open-Shell fork and Classic Shell before that. 

I read that ReactOS is a complete operating system still at the alpha stage. That's a big difference.
I've heard people speak highly of ReactOS and I wish the coding teams the best.
I myself have not tried it yet but might try if it gets to beta. 
Then I could maybe help there as well if I have any information that's useful.

Bye

**Comment by blackcrack** [comment]
you should understand and know what you speak about, in the other hand do you only bring in a pile of not need or not needable information , like a Cooking pot full of water with blubbering air in it. Make it full with couples of things, but it not use for the Ingestion... and what is left is a mountain of unusable information... because there be not you alone @CTVCAM8 .. there be many other Peoples who makes the same... there be Peoples where really programming , bring tonns of code and really need able informations like a Puzzle and they know what about they speak and have issues, where really be issues .. and not a entertainment like in a forum, therefore be forums, where be exchange of informations .. the "issues" in Github be not therefore are not meant for that .. otherwise would they are named Issuesforum and Brainthinkering place  ;) Therefore be Forum Boards and places where be extra for this ..  And on the other particular makes some considerations more work than it is useful..
lets us take the Startbutton.. you thin
k it is a easy picture, no it is not, it is a 3 Part Picture to have a animated Startbutton who works : 

![start_button-blue](https://user-images.githubusercontent.com/7925717/86998048-d67a5380-c1af-11ea-9b1f-5a917ce56928.png)

and this extra include in a svg or svgz makes extra work and if an other possible and other peoples who comes like you are and thinks about and all is make as svg and now a new thing where comes extra on it make the next complicate step where not really needs is there makes then more complicate if the programmers not think about the more easy hold and good to use thing.. if you understand what i mean.. i be more as 20 years on the way with Dos Win, WinNT and Linux (Mandriva, now Fedora) and there was manny ideas and manny things where not need, because the peoples be come away from the way.. lets look on the Mandrake, then Mandriva, now Openmandriva where is so becomes crappy that nobody it more use because, there was peoples and have in the start lead Peoples where have nothing understood about Mandrake Linux with Configuration Gui who have it easy bring OpenMAndriva to a real freaky without configuration-gui Linux that it now nobody more use.. and now.. have exactly they peoples no time anymore for developing further, because because they didn’t know what kind of garbage they made and broke the distribution and now don’t feel like it because nobody wants to use it anymore .. and my is bleeding my heart, because i was on it, in the background, since Gael it has start with Mandrake in the 1998/1999 and i have all feel with the distribution and the working and not working rpm's ... on this time was a "linuxconf" and Gaël Duval has with me mailed he want create a more better configuration tool like it is actual.. this was short behind Pierre send a RedHat to Gaël... jears later have start the OpenMandriva Community and i was one of they are where have a truth Wiki bulding up and whant bring back the Peoples to OpenMandriva, but a Bullshit Chairman have delete the Wiki and aaaaall the real truth information and have make a "non real" and all "the under the carpet" holding Wiki and had give OpenMandriva a bullschit way .. the Fellowing Chaireman, where was really a Mandrakeianer was later on a way where had a change to make no more the right way.. ...



```
Le vendredi 26 avril 2013 08:24:24, vous avez écrit :
> Hi,
>
> i have so far over 60% from the History and Adventure in the Wiki,
> if you want help, do it and complete it furter... , now can you say
> thank you to Gaël Duval with you Alias unter the tanks write 
>
> http://wiki.openmandriva.org/en/The_Adventure#Say_thank_you_to_Ga.C3.ABl_Du
> val_for_this_Distribution_and_founding_.28Alias_only_.2Fsign._to_big_.2Ag.2
> A.29


At Solutions Linux 2004 (Paris), i had together in front of me Gaël Duval and 
Joël Bernier (Linux-Kheops / Les logiciels du soleil / RedHat). Both have 
confirmed me this:
« In 1998, Joël sent a Redhat 5.1 to Gaël and this is the start point of the 
adventure. Without this shipment, Mandrake would not be born. »

Please insert it in the wiki and publish it. My mail was rejected and I have 
no time to search the reason... 


-- 
Pierre Jarillon - http://pjarillon.free.fr/
Vice-président de l'ABUL : http://abul.org
Microsoft is for computers what McDonald is for French gastronomy
```  

The Source of the Mail
<details>  

```  
From - Sat Apr 27 09:31:25 2013
X-Account-Key: account1
X-UIDL: 0M6SsR-1UgMl90gg7-00xve7
X-Mozilla-Status: 0011
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
Return-Path: <jarillon@abul.org>
Delivery-Date: Fri, 26 Apr 2013 22:30:33 +0200
Received: from smtp6-g21.free.fr (smtp6-g21.free.fr [212.27.42.6])
	by mx.kundenserver.de (node=mxeu0) with ESMTP (Nemesis)
	id 0M6SsR-1UgMl90gg7-00xve7 for blackcrack@blackysgate.de; Fri, 26 Apr 2013 22:30:33 +0200
Received: from azkar.localnet (unknown [82.233.65.171])
	by smtp6-g21.free.fr (Postfix) with ESMTP id 64040822D4
	for <blackcrack@blackysgate.de>; Fri, 26 Apr 2013 22:30:28 +0200 (CEST)
From: Pierre Jarillon <jarillon@abul.org>
Organization: ABUL
To: Blackcrack <blackcrack@blackysgate.de>
Subject: Re: [OM Cooker] You whant Say thank you to =?utf-8?q?Ga=C3=ABl?=, take a look to the history :
Date: Fri, 26 Apr 2013 22:30:27 +0200
User-Agent: KMail/1.13.7 (Linux/2.6.38.8-desktop-10.mga; KDE/4.6.5; x86_64; ; )
References: <CALfwWKzqsMQdGggsFZ5VVZ=vs3zzTk4rp0Q5sLBoSzTLauyDxA@mail.gmail.com> <CAGpK=z7++TA=nDj5ZeEK-OZ_KER6+oDmuKzfZe0oMiAUrUHpiw@mail.gmail.com> <517A1D98.7070100@blackysgate.de>
In-Reply-To: <517A1D98.7070100@blackysgate.de>
MIME-Version: 1.0
Content-Type: Text/Plain;
  charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Message-Id: <201304262230.27063.jarillon@abul.org>
X-UI-Junk: AutoMaybeJunk -96 (BAY);
  V01:FB7aYUQK:/iGlFM+Wi/YHv0eaSHTtzwPwOEu+swy/JN6LLZxdwg+H95VU++0
  erqB6dw9BTF6fpXnKtsQoFl5925oTpQ8zz2SQzMZkhPL1CG5wTHiKYsVEr946yal
  Y1F4lOl441TF3agscdvFmNffP4xf6KbcU+qOYMzVaproCU7UgaWCvoVcO/5QiRgy
  aeBxBLntVwOidbiHHn5g2DPbz2qZ1DlEkb8ULcdksYQrPkZBkWXyc/bAUputbwuH
  JNukaRgWwkhy224eAl040k1xCDP5qMyczp0/arEDDGo4q8YA+Q2XvIdo=
Envelope-To: blackcrack@blackysgate.de

Le vendredi 26 avril 2013 08:24:24, vous avez =C3=A9crit :
> Hi,
>=20
> i have so far over 60% from the History and Adventure in the Wiki,
> if you want help, do it and complete it furter... , now can you say
> thank you to Ga=C3=ABl Duval with you Alias unter the tanks write :)
>=20
> http://wiki.openmandriva.org/en/The_Adventure#Say_thank_you_to_Ga.C3.ABl_=
Du
> val_for_this_Distribution_and_founding_.28Alias_only_.2Fsign._to_big_.2Ag=
=2E2
> A.29


At Solutions Linux 2004 (Paris), i had together in front of me Ga=C3=ABl Du=
val and=20
Jo=C3=ABl Bernier (Linux-Kheops / Les logiciels du soleil / RedHat). Both h=
ave=20
confirmed me this:
=C2=AB In 1998, Jo=C3=ABl sent a Redhat 5.1 to Ga=C3=ABl and this is the st=
art point of the=20
adventure. Without this shipment, Mandrake would not be born. =C2=BB

Please insert it in the wiki and publish it. My mail was rejected and I hav=
e=20
no time to search the reason...=20

=2D-=20
Pierre Jarillon - http://pjarillon.free.fr/
Vice-pr=C3=A9sident de l'ABUL : http://abul.org
Microsoft is for computers what McDonald is for French gastronomy

```
  
</details>  


But the OpenMandriva was alreaddy shredded /pick to pieces / criticize severely
because 3 Peoples had mean, they must change the whole Distriebution and make it other.. 
with no correckt configuration Gui , so draktools  and Drakinstaller and also urpmi.. and so is become OpenMandriva over the last 8 years with a jump to rpm5 and a jump back to rpm4 , became a piece of crap.. 
and even I, although I use the heart bleeds (must use) as the last way to day today, Fedora as a server system down in my basement...
Now is Openmandriva a soulless Distribution where no more really be useable ...
And i hate the First Chairman for that !.. Not Itchka, this Dude is the best ever.. but how was make the first way for Openmandriva make, was the Bullshit ever.. but this was comes, because the 3 Peoples had not know what they makes.. and my holding out because i was only angry about the whole bullshit.. and had make over and over bullshit.. suuuper.. now it is OpenMandriva what it is.. a peace of huge bull bull bull shit !! and now it stank so that nobody really wants to touch it anymore because it just doesn't work properly any more because it works easy no more like it should..

.......

........

do you know the butterfly effect ?

this about bullshit !!

best regards
Blacky

---===<<<((([[[Blackcrack]]])))>>>===---
Blackysgate.de
Blackysgate.net

**Comment by CTVCAM8** [comment]
@blackcrack

Yes, I've read similar comments before from other coders who went out of their way making code,
then to find out later the new shiny looks or special effects quickly went out of fashion or options nobody used.
The program changed into something different and lost its way.
I see issues as problem bugs that need to be solved quickly.
I see Feature Requests as low priority as in possible future development.  
I assume it's up to the gatekeeper to determine if a Feature Request is worthwhile, or if the requester closes it themselves. 



Hello @bonzibudd 
I looked around the program a little.
I notice Ivo put some instructions in his code that auto picks the correct size classic grey start button image,
 (included in his program)
to match the small/large taskbar size. It's not DPI detection though. 
He didn't apply it to his special 12 frames animated shell start button.
I know already from making skins that Ivo had code that detects 144 dpi. 
So making extra code and bigger start button images inside the start menu program could theoretically work.


But asking for "custom" start button images made by a user to be integrated with code complicates it a lot more.
The user would still have to make all those different size images (I've made up to 6 sizes in some cases for 100%,125%,150%, 
and small/large taskbar), and identified in a way the code will find the correctly labeled image to display.

  
In my opinion, in this case, it may not be practical to include extra code just for users who have custom images to have it auto picked for the proper dpi size.
Even if there was code added to use an SVGZ file (@blackcrack mentions it's a lot of work), it's the user who has to make the big image.  So it looks like automation would not help a lot.!

**Comment by blackcrack** [comment]
no, i told. it is later more work for Peoples who not understand to make svg with pictures into and then is more work and more complicate to make some 3 part pictures, this "ISSUE" should be close instantly, it's no more worth to speak about..

**Comment by bonzibudd** [comment]
Well then, I suppose I'll close it. It's just a suggestion after all, I thought it would be worth a conversation. I was wrong. I am sorry.

**Comment by blackcrack** [comment]
:+1: 
@bonzibudd rather ask how something works that you then know whether it should be improved or not :)
because if you run onto without knowing and then try to change it without knowing of background, comes this really bad *twinkel*
