### ISSUE TITLE
Menu glass color does not seem to change saturation linearly 

### ISSUE THREAD

**Issue by bonzibudd** [Open-Shell/Open-Shell-Menu#396]
I am currently using Open-Shell to achieve the glass effect on the taskbar and the Start menu. I found that for the theme I am using, the opacity matches up well at Taskbar=40 and Menu=30. If I use a color that includes either 0% OR 100% saturation, the Taskbar and Start menu match up exactly. However if the color has a saturation that falls anywhere between there, the colors are different, almost like the Start menu's colorization is changing exponentially instead of linearly.

**Comment by CTVCAM8** [comment]
I think the original developer said somewhere in the Classic Shell forum,
that the menu skin is more complicated to match up to the taskbar, as there are more factors involved. 

My observations:
Taskbar. If I make a real 32-bit image for the taskbar with white r255,g255,b255, and 0/255 alpha transparency,
it seems to duplicate what it looks like when the glass taskbar is drawn internally without a taskbar image.
Looks simple enough - Change the "Taskbar opacity" setting and the color and opacity changes. 0 invisible to full 100 opaque. 

Start menu. The menu bitmap image and color mask work differently.  
The menu bitmap image can have varying amounts of alpha opacity for a gradient, borderlines, 
as well as varying amounts of RGB colors (normally black or grey with white for borders).
Now throw in a color mask that can have varying amounts of its own. It's quite a mix! 

The menu bitmap already has some transparency, 
so it seems the "Glass opacity" setting "0 to 100" is only going to add more opacity to what's on the bitmap. 
I could be wrong, maybe it divides by a certain amount.? 
Because of all that, that's why it's difficult to match the taskbar and menu up.
There is also another factor on Windows 10 where even when a menu color mask is disabled, glass color leaks through
unless glass opacity set to "0" 


But what would be great is a start menu that could be all done internally with Windows code, 
like the Classic .skin7 (does not have a menu bitmap)but have it with transparency, then the taskbar and menu would match exactly.

Maybe even with an acrylic look. Now that would be super. :)

**Comment by bonzibudd** [comment]
Interesting, I guess that makes sense when you have the different transparencies combined with the custom bitmap in the menu. Obviously if there was a universal solution, it could easily be implemented but that isn't really the case. Luckily, most of the colors that I want to achieve and match are doable, it just takes a bit of manual work, and of course the change won't stay if you change the system Aero color. Anyway, thanks for the input!
