### ISSUE TITLE
Is the hypen in the name necessary...

### ISSUE THREAD

**Issue by eacartwright** [Open-Shell/Open-Shell-Menu#397]
This is SUPER anal I know... I also understand I can just modify it myself. I'm just submitting that Classic Shell was known within the Windows Explorer environment as "Classic Shell" not "Classic-Shell". Now, I understand that there may be reasons to have non-spaces but it used to be: right-click > "Pin to Start menu (Classic Shell)" and now it's "Pin to Start menu (Open-Shell)" and I just think it would be more in line with your reincarnation if it lost the hyphen in the user-facing contexts. Just an idea!

**Comment by xcasxcursex** [comment]
I think it's good how it is, for a simple reason: You can search for it. Searching for "open shell" is going to get you lots of hits about molluscs ;) "open-shell", however, distinguishes itself by means of the hyphen. Naturally, having inconsistency in the naming would be undesirable, so having the hyphen remain in user-facing contexts makes sense - otherwise people go searching for the thing they see in their menus and get hits about, you guessed it - molluscs again!

**Comment by bonzibudd** [comment]
Hyphens are used frequently in programming, and would help distinguish the software from real shells. The hyphen is also useful because of some edge-case scenarios when using the keyboard to do something related to open-shell, which may or may not recognize an extra space.

**Comment by eacartwright** [comment]
You both have changed my mind. I dig it. Thanks for the insights.
