### ISSUE TITLE
PC Settings items are all missing

### ISSUE THREAD

**Issue by Dwedit** [Open-Shell/Open-Shell-Menu#424]
**Describe the bug**
On one computer, my installation of ClassicShell has a complete set of "PC Settings" items available, they appear as search results.  These items have a blue settings Gear icon, and redirect to pages on the Windows 10 settings app, or to control panel entries.  Examples of such items include "Programs and Features" (control panel item), "Add or Remove Programs" (Windows 10 settings page), "Add, Edit, or Remove other users" (windows 10 settings page), Bluetooth Settings (windows 10 settings page), etc.  I think there are 346 of them total.

On another installation (Openshell), none of these items exist at all, and I can't figure out why.

**To Reproduce**
Don't know how to reproduce this.  Don't know why one installation has all settings intact while another installation is missing all of them.

**Expected behavior**
The 346 "Settings" items should be available.

**Screenshots**
A search for "Bluetooth"

Working:

![Screenshot](https://i.imgur.com/S9KWojV.png)

Not Working:

![Screenshot](https://i.imgur.com/ObGkvmT.png)

**Version:**
The "Working" version seems to be Classic Shell 4.3.0.0, an installation that was upgraded several times over the history of a computer.

The "Not Working" version seems to be OpenShell 4.4.142.0, and was a fresh installation.

Windows 10 version is 10.0.19041.450 on both.

**Comment by ge0rdi** [comment]
This is known issue. See #57 for more details.

To sum it up, older Windows versions had modern settings stored in `.settingcontent-ms` files and these were indexed and known to `Open-Shell`.
New Windows versions (since 1709 or so) have modern settings stored in different format that cannot be easily added to `Open-Shell`.

Those old files could be present also on never Windows versions if you did upgrade (they are definitely not on clean installations). But even then they may be inaccurate and won't contain new settings.

I'm currently finishing support for that new format of modern settings. So hopefully it will be available in nightly builds soon (I can't promise anything).
I will announce it in original #57 issue, so please subscribe to it so you will get notified.

**Comment by Dwedit** [comment]
Thanks, just copied the directory (my path was `C:\Users\USERNAME\AppData\Local\Packages\windows.immersivecontrolpanel_cw5n1h2txyewy\LocalState\Indexed\Settings\en-US` ) and it works perfectly.
