### ISSUE TITLE
Add option to disable shutdown hotkeys

### ISSUE THREAD

**Issue by LudiusMaximus** [Open-Shell/Open-Shell-Menu#447]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to use the search box, but accidentally my mouse cursor comes to rest over the "Shut down" entry, which then extends automatically. Because when I then type an "r" into the search box, my system automatically restarts immediately.

**Describe the solution you'd like**
The best thing would be an option to disable the "r" hotkey and all other shutdown hotkeys ("l" for log off, etc...).

**Describe alternatives you've considered**
Otherwise, I would at least like a prompt so that I can deny the restart.

**Comment by ge0rdi** [comment]
I'd suggest to disable automatic sub-menu opening via:
`Open-Shell settings` -> `General Behavior` -> `Menu delay`  (set big number there).

In fact I'd rather disable that automatic opening by default.
I don't quite get what it is good for when one can simply click mouse button (no need to wait till sub-menu is opened).

**Comment by LudiusMaximus** [comment]
I kind of like the automatic openning (I have set it to relatively fast 200) for the menu folders. If I could just disable it for the Shutdown button, it would be fine, too.

**Comment by ge0rdi** [comment]
> If I could just disable it for the Shutdown button, it would be fine, too.

That's not possible currently.

For now I'd just recommend a workaround:
Use keyboard when opening Start menu to do search. You need to type via keyboard to search, so it makes also sense to open menu using `Win` key.
And then there will be no problem with accidental sub-menu opening.

**Comment by ge0rdi** [comment]
Related to #407 .

**Comment by LudiusMaximus** [comment]
All right, using the Windows-Key to be on the safe side is in fact a good idea. Thanks!

**Comment by danielmmmm** [comment]
Thanks for pointing out the Windows-Key.

I noticed that hot-keys only activate after typing any character while the mouse cursor is hovering over a menu. When the mouse cursor rests on single items, typing does not activate hot-keys and only the search box receives input.
My workaround is having all shutdown items (sleep, restart, shut down) as single items above the search box, instead of the shutdown menu. The next menu in my setup is the settings menu. Since it is four items away from the search box, I am less likely to place the mouse cursor there by accident.

I too would appreciate the possibility to disable hot-keys ... some time in the future :-)

**Comment by eddiekk** [comment]
+1 for this. So annoying when the computer decides to restart on its own when searching for something

**Comment by AidanConnelly** [comment]
Is there an option to disable all hotkeys?

**Comment by ge0rdi** [comment]
In [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build it is possible to configure accelerators to trigger only when Alt is pressed (`Require Alt key for accelerators` setting) or disable keyboard accelerators completely (`Enable accelerators` setting).
