### ISSUE TITLE
Display Settings search results above Control Panel ones

### ISSUE THREAD

**Issue by NebelNidas** [Open-Shell/Open-Shell-Menu#481]
As more and more settings are being moved towards the Settings app, thus removing them from Control Panel, latter is increasingly getting less and less important, especially since many of its entries now only point to the new Settings anyway. It just doesn't make sense anymore giving Control Panel entries a higher priority than the new Settings ones (at least for newer Windows versions. We could implement a check for let's say Win10 >= 1903 and enable this new behavior only for these users).

Current behavior:
![image](https://user-images.githubusercontent.com/48808497/94662608-efa32400-0308-11eb-8321-61f3714aced1.png)

Requested behavior:
![Settings search results above Control Panel ones](https://user-images.githubusercontent.com/48808497/94663897-815f6100-030a-11eb-9c61-05cace437705.png)

It would probably also make sense to rename `Settings` to `Control Panel` and `Modern Settings` to `Settings`.

**Comment by ge0rdi** [comment]
Related to #23 

> It would probably also make sense to rename Settings to Control Panel and Modern Settings to Settings.

Yup, definitely. To match actual items in start menu:
![image](https://user-images.githubusercontent.com/2453094/94665953-15322c80-030d-11eb-9ada-5231fb633c8d.png)

**Comment by bonzibudd** [comment]
I definitely agree with this. However, it might be better to keep it the same in Windows 8(.1) since it still has all of the non-Modern UI features in it, unlike Windows 10 which relocated options. This probably isn't very important though.

> It would probably also make sense to rename `Settings` to `Control Panel` and `Modern Settings` to `Settings`.

That would be nice as well. In this sense, Windows 7 should stay the same because that is how it is displayed there. I think it was an intentional decision from Microsoft to name that section "Settings" instead of "Control Panel" since technically, there are some applets which aren't inherently part of the Control Panel. 

I think that theoretically, both categories should be merged into one, however I understand that may not be the best solution because of the limited number of items which Search can display without expanding the list. But I would be more than happy with a prioritization of Settings items over Control Panel.

**Comment by XenHat** [comment]
![image](https://user-images.githubusercontent.com/980408/97473522-73a8f580-1921-11eb-8f3a-5ecf6efc768f.png)
Very happy with this. Great job.

**Comment by rezaport** [comment]
hi thank you for this great app.
Please give user the freedom of choice for changing the seeing control panel results over settings results.
Even in win10 version 21h2 very good configurations are still  in control panel
and Microsoft likely will not change this  because win10  maintenance support date has ended.
