### ISSUE TITLE
Make taskbar transparent (0-100)

### ISSUE THREAD

**Issue by MM-73** [Open-Shell/Open-Shell-Menu#492]
**Describe the bug**

For me, unfortunately, making the taskbar transparent from 0-100 doesn't work.

**To Reproduce**

Open shell menu
Show all settings
Taskbar
Customize taskbar
Taskbar opacity: 85 (value chosen by me)

**Expected behavior**

I would have expected that the taskbar would no longer be completely black.

**Screenshots**

**Version:**

 - Open-Shell: 4.4.152
 - OS: Windows 10 Professional 64 Bit - Version 2004

**Additional context**

I wanted to make the taskbar a bit transparent.

That's why I set the value for Takbar opacity to 85 under Customize taskbar in OpenShell.

Then I restarted the PC, but the taskbar remains black as before.

In OpenShell, the value 85 is still entered under Takbar opacity, but this value does not seem to have any effect.

I tried several values for it (0 - 100) unfortunately always with the same result.

**Comment by bonzibudd** [comment]
If you could, it would be helpful to attach a screenshot of the Settings page with the Taskbar settings, and an image of what the Taskbar looks like.

Also, I don't know if this is related, but due to a change in Windows, the "Glass" transparent options no longer work properly if you have transparency disabled in Windows Personalization settings. I would try both the "Transparent" and "Glass" options to see if they make a difference.

**Comment by MM-73** [comment]
Thank you for the feedback and the tip. :)

I have now activated transparency in the Windows Personalization settings and now it works fine.

I wish you a nice weekend.
