### ISSUE TITLE
Setup - Warning 1946. Property ...~

### ISSUE THREAD

**Issue by blackcrack** [Open-Shell/Open-Shell-Menu#507]
**Describe the bug**
get by setup a Error, Can not make a Link, 
look the screenshoot.

**To Reproduce**
1. Go to Nightly 
2. Click on 'the files'
3. download the files
4. Klick on the Setup-File 
5. fellow the Instrucktions
6. See error

**Expected behavior**
nice and clean Setup
**Screenshots**

**Version:**
 - Open-Shell:  4.4.161
 - OS:  Windows 7 Pro ESU 9

**Additional context**
nope, not need.  
  
  
![Screen 00001](https://user-images.githubusercontent.com/7925717/97006507-45ea3800-1540-11eb-87c4-5e6b23ffcf0d.jpg)

**Comment by ge0rdi** [comment]
The problem is that Windows 7 doesn't recognize `System.AppUserModel.ToastActivatorCLSID` property name (it is used for update toast notifications). So we'd need to set property via GUID.

It is described here:
https://docs.microsoft.com/en-us/troubleshoot/windows/win32/warning-1946-when-you-install-installer-package

I did initial test and it seems to be working well.
Will submit PR soon.

Thank you for reporting.

**Comment by blackcrack** [comment]
My pleasure! 
for give my 2 cent's :)
best

**Comment by patoniilista** [comment]
Hi! I got the same warning on Windows 10 2004, Open-Shell version 4.4.160.

![2021-03-02 01_57_40-Issues · Open-Shell_Open-Shell-Menu - Chromium](https://user-images.githubusercontent.com/72221896/109599936-f07bf400-7afa-11eb-9e5d-7eb82c8247d8.png)

**Comment by blackcrack** [comment]
@patoniilista , please download the latest Build :  

https://ci.appveyor.com/project/passionate-coder/open-shell-menu/build/artifacts

best
