### ISSUE TITLE
Help shows wrong version number (and also fails to load initially)

### ISSUE THREAD

**Issue by scooterrodriguez** [Open-Shell/Open-Shell-Menu#524]
**Describe the bug**

A. I have verified that I am running Open Shell, version 4.4.160. However, Open Shell's Help window says I'm running version 4.3.1.

B. Here's a separate but related bug: When I initially open the Help window, I get a "Can't reach this page" error. (•Make sure the web address //ieframe.dll/dnserrordiagoff.htm# is correct)

**To Reproduce**

Bug A:
1. When I open Open Shell's settings and... 
2. Click Help
3. It opens the Help window which says I'm running "Version 4.3.1 - general release" 

Bug B:
1. When I initially open Open Shell's settings...
2. and click Help...
3. When the Help window is displayed, it shows a "Can't reach this page" error. 

However, if I click the purple book icon beneath the "Open-Shell" icon on the top-left, and then click back to the topmost "Open-Shell" icon, the bug resolves itself and loads the page correctly (except with the aforementioned incorrect version number.)

**Expected behavior**

Bug A: I expect the actual version number to be displayed in the initial Help window instead of showing the wrong version number. 

Bug B: I expect the Help window to load without error the first time I open it.

**Screenshots**
![openshell00a1](https://user-images.githubusercontent.com/13073704/98453765-c60cc200-212a-11eb-9fc6-e6d62a79546d.png)
![openshell0](https://user-images.githubusercontent.com/13073704/98453767-ca38df80-212a-11eb-85e2-7e7d702ee2d6.png)
![openshell1](https://user-images.githubusercontent.com/13073704/98453769-cc02a300-212a-11eb-8c08-a2b617ec2a83.png)

**Version:**
Don't worry about it. She's fast enough for you, old man. 

**Additional context**

**Comment by scooterrodriguez** [comment]
Oh yeah, and looking at my last screenshot, it shows your copyright as being 2017-2018. Needs to be updated to 2020.

**Comment by ge0rdi** [comment]
Thank you for reporting.

Honestly, help requires complete revamp. Showing wrong version is just tip of an iceberg.
Very little was changed in help since its original `Classic-Shell` version. It contains links to `Classic-Shell` site, wrong information about supported OS, etc.

Will be great if someone could take care of modernizing it.
This doesn't require programming skills I guess, so anybody willing to do it could submit PR with changes.

P.S. It is always better to report separate bugs/issues separately. It helps tracking a lot and decreases probability that something will get overlooked.

**Comment by bonzibudd** [comment]
I wonder if it may be possible to automatically update that version number via the installer.

**Comment by blackcrack** [comment]
> I wonder if it may be possible to automatically update that version number via the installer.
  
the binary of installer have a Version specification , because it's a binary.. and the binary as so, because it's just a variable where be possible for setting up by building.. (automatic or non automatic), take a look on you cmd, you can "set theversion=1.1.66" in the commandline so cmd and you can call it via " echo %theversion% " , this can you add at the compiling of the binary in hardcoding, this works not over the registry over WinNT.. so can you update it if you update the binary, so the StartMenu.exe and the help-file. you can find it there :  
https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/StartMenu/StartMenu.rc  
Line 84

what i have changed .. and submit a patch ..

best
Blacky

**Comment by ge0rdi** [comment]
@bonzibudd 
Version is part of `Main.html` file that is compiled into help:
https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/Localization/English/Main.html#L23

You would need to change the html file during build process (there is `CS_VERSION` environment variable that holds actual version).

Or somehow modify html to access some help properties at run-time, but I'm not sure if that is even possible (I'm not familiar with Windows help much).
