### ISSUE TITLE
Replace currnt Metro skin with Fluent-Metro 

### ISSUE THREAD

**Issue by asianmusicguy** [Open-Shell/Open-Shell-Menu#531]
@ge0rdi  I have been using it and its miles ahead of the default skin currently https://github.com/bonzibudd/Fluent-Metro/tree/v1.2
if @bonzibudd  was willing of course?

**Comment by bonzibudd** [comment]
I personally don't think this is a good idea, most people are happy with the current default. Also, my skin requires a lot more manual configuration, which wouldn't be obvious to the majority of people. Mainly things like color scheme and padding don't work fully unless you change other settings. There are other problems, like compatibility with other language files, most custom skins including mine only support static English text.

I appreciate your interest, but I think it would be better if they stay separate.

**Comment by blackcrack** [comment]
if it's need, it is here :  
https://github.com/bonzibudd/Fluent-Metro/releases

@Open-Shell

We should have a link on the Open-Shell Homepage to 
a own  and actual Open-Shell Forum Forum
where it is able to link in the github sides to the Skins

To have ever the old Homepage from Classic-Shell is a lag behind and not a feeling of actuality.
The Open-Shell need an own Forum (like PHPBB3 or simplemachines.org) and the Classic-Shell could be linked as "Resources from the predecessor" to have a correct official Forum for -Windows Desktops- (?Open-Shell **for Windows Desktop** Startmenu?) 
Open-Shell should slowly stand as his own stable Project also in a official Forum, therewith 
should also exist a Official Open-Shell Forum with reference to the original Classic-Shell Forum.

therewith could with Open-Shell a official own forum at the Github-Homepage linked, attract more Developers in programming, Skinning and others, because have a real clean starting point by side of code part and make a possible for rss-feed (likeQuiterss or rss-apps at handys and Nextcloud Rss-App) from a Forum (to read every morning what's going on) and make it more interesting because to be a part of it speak together into a clean Forum/Portal for Desktops .. (and not so an cell-phone-crap my personally opinion)

best regards
Blacky

**Comment by bonzibudd** [comment]
@asianmusicguy 
We can probably close this issue. 

One last note, I'm currently working on a Windows 10 skin which could be added to Open-Shell, to replace the default. It's somewhere in-between the Metro skin and Fluent metro. You can get updates here: https://github.com/Open-Shell/Open-Shell-Menu/issues/538

However more importantly, we probably shouldn't impose any changes with no option to revert back.

**Comment by NuraliMedeu** [comment]
@bonzibudd, I understand that you don't want to annoy some of the users of Open-Shell by making Fluent-Metro the default. However, I think you should include it as an option alongside the current Metro skin, because it is a very good skin.
