### ISSUE TITLE
[Request] change start menu color

### ISSUE THREAD

**Issue by ShlomiD83** [Open-Shell/Open-Shell-Menu#586]
at the moment I can choose the taskbar color but not the start menu itself.
is there a way you can implement this feature?

thanks!

**Comment by bonzibudd** [comment]
For Start Menu skins that support this, you can go to the "Menu Look" tab and scroll down to the option "Override glass color." However, the default "Metro" skin doesn't support this because it uses system accent colors for the background. You will need to switch to a different skin like the Windows 8 skin, however those do not support overriding the white section on the left-hand side.

If you want to override the entire menu color, the only option I know of is my skin I am working on here: https://github.com/Open-Shell/Open-Shell-Menu/issues/538 (Latest version at bottom of post).

To apply it, extract the contents and copy them to C:\Program Files\Open-Shell\Skins. Now if you open the Open-Shell Menu settings, it will appear under the Skins tab. With the skin applied, you can click the "More Transparent" option to make the color appear in the entire menu. Then you can go back to the "Override glass color" option and change it to use a custom color.

**Comment by ShlomiD83** [comment]
> For Start Menu skins that support this, you can go to the "Menu Look" tab and scroll down to the option "Override glass color." However, the default "Metro" skin doesn't support this because it uses system accent colors for the background. You will need to switch to a different skin like the Windows 8 skin, however those do not support overriding the white section on the left-hand side.
> 
> If you want to override the entire menu color, the only option I know of is my skin I am working on here: #538 (Latest version at bottom of post).
> 
> To apply it, extract the contents and copy them to C:\Program Files\Open-Shell\Skins. Now if you open the Open-Shell Menu settings, it will appear under the Skins tab. With the skin applied, you can click the "More Transparent" option to make the color appear in the entire menu. Then you can go back to the "Override glass color" option and change it to use a custom color.

very nice, it works.
how can I change space between every row in "All Programs"?

**Comment by bonzibudd** [comment]
This skin is still being developed, so that size isn't completely final. However, this one should have better spacing: 
[Win10 Better programs.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/5744858/Win10.Better.programs.zip)

**Comment by ShlomiD83** [comment]
> This skin is still being developed, so that size isn't completely final. However, this one should have better spacing:
> [Win10 Better programs.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/5744858/Win10.Better.programs.zip)

Thanks.
I've also installed this skin "Fluent-Metro", it's very very nice.
