### ISSUE TITLE
Need help for Classic Theme and OpenShell

### ISSUE THREAD

**Issue by malvinas2** [Open-Shell/Open-Shell-Menu#605]
Applying my [Classic Theme for Windows 10](https://github.com/malvinas2/ClassicThemeForWindows10) I experience two issues within OpenShell. 
Does anyone know what I have got to change within the theme to resolve these problems? 

**Issue 1**
[Check marks (radio buttons) in dialog boxes of OpenShell are not visible](https://github.com/malvinas2/ClassicThemeForWindows10/issues/9)

<img src="https://user-images.githubusercontent.com/25912063/104230483-eff5a400-544d-11eb-816d-a1c0826318d8.png" width="700" />

**Issue 2**
[Triangle icons do not appear in Explorer Navigation Pane](https://github.com/malvinas2/ClassicThemeForWindows10/issues/8)
The style of the nodes for the folder tree in the navigation pane can't be changed. No matter if 'XP Simple' or 'Vista' is choosen, the pane always shows 'plus'-signs to expand the folders. 'Triangle'-signs are never displayed.

<img src="https://user-images.githubusercontent.com/25912063/104227731-22050700-544a-11eb-8acb-1a1143cf433e.jpg" width="320" /> <img src="https://user-images.githubusercontent.com/25912063/104228090-a5265d00-544a-11eb-9e25-6d31d7514b7d.png" width="400" />

**Comment by bonzibudd** [comment]
I can only comment on the first issue. 

This has been previously discussed: https://github.com/Open-Shell/Open-Shell-Menu/issues/142

It only seems to affect some highly-customized themes. For example, I tried the "Aero 7" theme and it worked fine. It might be the result of some weird way of accessing skin resources on the part of Open-Shell, but I wouldn't have any insight into that as I'm not a developer.

**Comment by malvinas2** [comment]
@bonzibudd 
Yes, that's exactly the problem! And as already mentioned in [#142](https://github.com/Open-Shell/Open-Shell-Menu/issues/142) the strange point is, that OpenShell is the only program affected by this error. So yes, there must be something wrong with the visual style, but also with OpenShell itself.

**Comment by bonzibudd** [comment]
Hey, I haven't been able to figure this out, but something I did notice is that looking at the checkboxes and toggles in the default Windows theme, Open-Shell seems to ignore the hovered/selected variants of those buttons. That seems to suggest that there is some weirdness around how Open-Shell displays those buttons.

However, looking at the "Show all settings" button at the top of the window, it works just fine with the custom skins. So that makes me think that the entire middle section of the Settings window behaves differently than the frame around it.

Selection for "Show all settings" button:
![image](https://user-images.githubusercontent.com/61938331/119694060-e0826080-be1a-11eb-83e4-579a18ac291c.png)

Missing on buttons within rest of window:
![image](https://user-images.githubusercontent.com/61938331/119694160-fb54d500-be1a-11eb-8693-07b374c50ad9.png)
