### ISSUE TITLE
Upgrade question?

### ISSUE THREAD

**Issue by DrTeeth707** [Open-Shell/Open-Shell-Menu#64]
I just want to be sure of something. I have an old Classic Start Menu setup that has been so customised, an upgrade to Open shell is out of the question unless either it will import the old program's settings or I can import them manually.
Is it possible to do either at the moment?
I am over the moon that this excellent utility is again under active development. If possible, I would contact the original programmer to see if he will put an announcement on his site to that effect to increase uptake.
Cheers
DrT

**Comment by david-rahrer** [comment]
I'll let one of the developers answer but this other issue thread may be of help: #28

**Comment by ibuprophen1** [comment]
@DrTeeth707, This is exactly as what @david-rahrer had pointed out. 

I've looked at various options regarding a form of Migration to Open Shell from its predecessor Classic Shell. 

After scrubbing through some of the Source Code files, this type of implementation would require much more work than I feel would really be worth dedicating the time for. 

All is not lost... 

I feel that this would be best done as a separate development that's dedicated for this specific task. 

I've already started working on this but, to be honest, I've also got other Windows/Android Developments that I've been bouncing around on as well. 

I doubt that it will take that much longer to complete depending on how it tests out. This isn't a difficult task but, does require some careful commands as well. 

The 3 Open Shell developers (@ge0rdi, @coddec and @XenHat) are aware of this. As a professional courtesy, and since this does have to do with their project, they will be provided the release to review and give the final approval before publicly released. 

I hope that I had explained this okay via text... :-) 

This and any further information by myself will be provided on the following issue... 

https://github.com/Open-Shell/Open-Shell-Menu/issues/28

Thank you very much for your time and understanding with this! :-) 


~Ibuprophen

**Comment by DrTeeth707** [comment]
Ibuprofen*
I had read the other thread. Classic Shell's layout was quite difficult to get used to as it had so many options. If this new branch does not have a facility to somehow migrate settings, this very worthy effort will be shooting itself in the foot as many might not the effort worthwhile to migrate. That was my only reason for asking.

I would like to offer my services as a beta tester. I always backup daily and know my way around a PC. I currently multiboot my main PC. It has two versions of windows on it (win 8.1 and 7) and approx 9 Linux distros, all in primary partitions on the same drive. I have much more room to install dedicated version of Windows. For some reason, though I can install windows 10, it crashed on booting the last time I tried it. As I HATE it, it is no loss.

Cheers

DrTeeth
* Nice handle. I prescribe you several times a day in my day job ;-).
