### ISSUE TITLE
dark mode please

### ISSUE THREAD

**Issue by Yellow-Flash-1** [Open-Shell/Open-Shell-Menu#733]
it lacks dark mode

**Comment by bonzibudd** [comment]
Do you mean the Start menu, or File explorer?

**Comment by Yellow-Flash-1** [comment]
im talking about start menu
i wish it could match the theme of the system like the official start menu

**Comment by bonzibudd** [comment]
This isn't available for the default Start menu skin, but I have a skin that matches the system colors: [Fluent-Metro](https://github.com/bonzibudd/Fluent-Metro)

**Comment by Yellow-Flash-1** [comment]
i have exactly that version

**Comment by Yellow-Flash-1** [comment]
i have that exact version

**Comment by bonzibudd** [comment]
Were you able to apply the skin? The instructions to install are [here](https://github.com/bonzibudd/Fluent-Metro#installation), and the release is [here](https://github.com/bonzibudd/Fluent-Metro/releases/tag/v1.5) if you need it. If so, you can close the issue.

**Comment by blackcrack** [comment]
@bonzibudd , could you not make a Startmenuskin who support Default colors and also the actual Colorsheme, include Darkmode "api" Color ? so.. could be a idea.. if i see your Win10 Skin, but this with System/defaultcolors

**Comment by bonzibudd** [comment]
@blackcrack I should be able to add something like that to the Win10 skin. For Fluent-Metro, it already has options to use static and metro colors instead of light/dark. However if you want the colors to be backwards compatible with older versions like Win7, that's not currently possible because Open-Shell will give an error to Win7 if there's any mention of a "modern" color.

**Comment by Yellow-Flash-1** [comment]
sorry i thoudht its you who closes it
