### ISSUE TITLE
Upgrade from Classic Shell 4.3.1 in preparation for Windows 11

### ISSUE THREAD

**Issue by ctp9** [Open-Shell/Open-Shell-Menu#777]
Hi all,

It's not an issue but I'd like to receive your expert advice on how to correctly upgrade + prepare the environment before Windows 11 officially gets forced on everyone:

I've been running Classic Shell 4.3.1 since 2017 and haven't had any issues across Windows 10 upgrades - it's been solid and very stable across every major upgrade. Unfortunately, it won't be the case with Windows 11 looming around the corner...

What is the correct way to upgrade from Classic Shell to Open-Shell? In-place upgrade? Clean installation? Do I need to export my settings to "Menu Settings.xml" and install Open-Shell from scratch and then import the menu settings? Sorry for asking too many questions but I am slightly confused after having had read all the threads here regarding the upgrade procedure.

Thanks for your help in advance.

**Comment by Diwax** [comment]
My issues exactly! This upgrade totally screwed up everything! I finally uninstalled Shell and now I can't get back my stuff the way I preferred and was comfortable and familiar with. I'm not sure if I want to take a chance to reinstall Classic Shell 4.3.1 with the upgrade of Windows 11. I initially thought the issues were with Shell and now realize it is the recent integration of Windows 11 -which sucks with so many issues!

________________________________
From: ctp9 ***@***.***>
Sent: Monday, July 5, 2021 3:23 AM
To: Open-Shell/Open-Shell-Menu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Open-Shell/Open-Shell-Menu] Upgrade from Classic Shell 4.3.1 in preparation for Windows 11 (#777)


Hi all,

It's not an issue but I'd like to receive your expert advice on how to correctly upgrade + prepare the environment before Windows 11 officially gets forced on everyone:

I've been running Classic Shell 4.3.1 since 2017 and haven't had any issues across Windows 10 upgrades - it's been solid and very stable across every major upgrade. Unfortunately, it won't be the case with Windows 11 looming around the corner...

What is the correct way to upgrade from Classic Shell to Open-Shell? In-place upgrade? Clean installation? Do I need to export my settings to "Menu Settings.xml" and install Open-Shell from scratch and then import the menu settings? Sorry for asking too many questions but I am slightly confused after having had read all the threads here regarding the upgrade procedure.

Thanks for your help in advance.

**Comment by Diwax** [comment]
YES, AND YES...What is the correct way to upgrade from Classic Shell to Open-Shell? In-place upgrade? Clean installation? Do I need to export my settings to "Menu Settings.xml" and install Open-Shell from scratch and then import the menu settings?
 I am slightly confused after having had read all the threads here regarding the upgrade procedure.

________________________________
From: ctp9 ***@***.***>
Sent: Monday, July 5, 2021 3:23 AM
To: Open-Shell/Open-Shell-Menu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Open-Shell/Open-Shell-Menu] Upgrade from Classic Shell 4.3.1 in preparation for Windows 11 (#777)


Hi all,

It's not an issue but I'd like to receive your expert advice on how to correctly upgrade + prepare the environment before Windows 11 officially gets forced on everyone:

I've been running Classic Shell 4.3.1 since 2017 and haven't had any issues across Windows 10 upgrades - it's been solid and very stable across every major upgrade. Unfortunately, it won't be the case with Windows 11 looming around the corner...

What is the correct way to upgrade from Classic Shell to Open-Shell? In-place upgrade? Clean installation? Do I need to export my settings to "Menu Settings.xml" and install Open-Shell from scratch and then import the menu settings? Sorry for asking too many questions but I am slightly confused after having had read all the threads here regarding the upgrade procedure.

Thanks for your help in advance.

**Comment by anonimuos** [comment]
Backup all your settings to XML for the menu and Explorer. Then do in-place upgrade. Open Shell will migrate your settings, however note that the directory path changes to C:\Program Files\Open-Shell so if you had any custom skins, icons, commands in the old path at C:\Program Files\Classic Shell\ it may break. Just copy any missing files from C:\Program Files\Classic Shell\Skins to C:\Program Files\Open-Shell\Skins and do not overwrite any existing files as Open-Shell will have updated skins.

In case anything is still broken, import the XMLs and update any broken icons, commands to their new paths after import.

**Comment by BartZorn** [comment]
Well... that is not what I saw. I am running preview Windows 11 in a Hyper-V VM and ClassicShell just runs fine.
There are a few cosmetic issues:

- The classic shell start button does not replace the Windows start button. Instead, it appears left on the task bar, as usual, while the Windows Start menu button remains in the middle section.
- I normally configure ClassicStartmenu to open the Win+X menu on right click. This does not work on the ClassicStartmenu, but still does on the Windows Start menu button.

Pleas note that I am NOT a programmer. I just hope that this information is useful to the Open Shell team.
