### ISSUE TITLE
After Update for Windows 10 Click on [Start] does not open menu

### ISSUE THREAD

**Issue by HL-1234** [Open-Shell/Open-Shell-Menu#804]
**Describe the bug**
After an Update for Windows 10 the Click on [Start] does not open the Open Shell menu. The update was: 
2021-07 Cumulative Update for Windows 10 Version 20H2 for x64-based System (KB5004296)

I have install the update. Then a click on [Start], to open Open-Shell menu, it flashes and did not open.
An Open-Shell update to the latest Version 4.4.160 doesn't help.
After de-install the Windows update all things are fine again.

**To Reproduce**
Install the Windows update for Windows 10 Version 20H2 for x64-based System (KB5004296), if it hasn't do to with somthing other on my PC.

**Expected behavior**
Open the Open Shell menu

**Version:**
 - Open-Shell: [e.g. 4.4.160]
 - OS: [Windows 10 20H2 (Build 19042.1110] before Update - with this build version, it's ok

**Additional context**
Latest on Twitter I tell Microsoft I do not need the new Microsoft menu for Windows 11, I always use Open Shell to organize the entries there by myself. But I don't know if there is an context.

**Comment by thisismy-github** [comment]
This is caused by the new "news and interests" taskbar panel, which only appears while the taskbar is positioned at the bottom, and has bugs that are caused by the panel being enabled while on an alternate taskbar position.

To fix: move your taskbar to the bottom, right click the taskbar, disable the news and interests panel, and restore your taskbar. Everything should be back to normal afterwards.

**Comment by HL-1234** [comment]
@thisismy-github Thanks, I follow your instruction and that had fixed the problem for me.
Thank you very much for the quick response.

**Comment by HL-1234** [comment]
The issue could be fixed.
