### ISSUE TITLE
Support for Windows 11 - mouse movements not working correct using Open-Shell 

### ISSUE THREAD

**Issue by boernerf** [Open-Shell/Open-Shell-Menu#858]
**Describe the bug**
After the update to Windows 11, mouse movements are not correct after pressing the "Start"-button until leave Open-Shell

**To Reproduce**
1. Click on 'Start'
2. Move the mouse to select programs
3. mouse and selections just move around all above the screen

**Expected behavior**
precise mouse movements

**Version:**
 - Open-Shell: [e.g. 4.4.160 and 4.4.169]
 - OS: [e.g. Windows 11 21H2, 22000.194]

**Additional context**
Open-Shell is the only application with this behavior of the mouse movements

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Can you make a screencast/video of your issue? It is necessary for the developers to reproduce the issue, only then they can fix it. For that you need to give as much info as possible and some screenshots/video. Under what conditions it happens etc. Because so far it isn't happening on my Windows 11, nor has anyone else reported it yet.

**Comment by ge0rdi** [comment]
Please, use latest `Open-Shell` build. It should be more compatible with Windows 11.
