### ISSUE TITLE
Can i also use it for Windows 11?

### ISSUE THREAD

**Issue by kosuodhmwa** [Open-Shell/Open-Shell-Menu#884]
If no: Would you make that possible in future?

Thank you very much for your feedback.

With kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
Thank you very much for your feedback.

**Comment by GlassedSilver** [comment]
When Microsoft went from the narrow 2000-style start menu to the XP menu - I liked it.
When Microsoft went from the XP menu to Vista - I liked it.
When Microsoft went from the Vista menu to 7 - I still liked it.
When Microsoft went from 7 to 8 - I refused to update.
When Microsoft went from 8 to 8.1 - I was hesitant about the new style start menu (now that it was more like the 10 style) - but by the time I could make a decision....
Microsoft already gave us 10, which I held out for until 2019 I think. And boy - I liked the 10 menu. (even - yes especially so - the live tiles. Weather, favorite pictures, a sneak peek at my mails, my to-do's... everything at a glance often enough, so I get to enjoy that visibility, but without being always in my face or never at all! Perfect balance!)
When Microsoft presented Windows 10X - meh... as long as they keep that to portables... That's alright, maybe.
When Microsoft hastily decided that Windows 10X is dead and needs to IMMEDIATELY replace Windows 10... I did not like it and for the first time I am considering Classic/Open Shell. After giving Windows 11 a LENGTHY maturing process that is. No way in hell will I get onto that train anytime soon.

That's my Classic Shell story. Always looked from the sidelines, always felt that it's nice that this kind of project exists, never felt a need in the long-run, but since Microsoft is obviously burning bridges on a very fundamental technical level like outright out phasing certain registry keys, options, etc... - maybe Open Shell will be my first go-to when Microsoft eventually forces me away from Windows 10 or ruins that as well in some "feature update".

Stay strong guys, keep the project alive. We need you more than ever seeing how Microsoft is very dead set on making Windows 11 resemble a nonfunctional "getting in your way" toy OS as much as possible.

**Comment by blackcrack** [comment]
You as Member of this Open Shell users group like we all, can help to hold it at run, i have ask for get it under GPL or to upload here to set it free for all..
but your adventure is also sweet so far, so stay at this group of peoples and help with to hold it at run..

best

**Comment by WSLUser** [comment]
`i have ask for get it under GPL or to upload here to set it free for all..`

MIT is freer than GPL. Anybody using MIT from legal perspective don't like touching GPL stuff. But GPL projects can easily use MIT stuff without nearly as many legal issues. Far easier to ingest MIT than GPL.

**Comment by kosuodhmwa** [comment]
Works - looks a lil bit strange but it works.

Like a mixture of Win10 and Win11...  :-) 

![image](https://user-images.githubusercontent.com/24782840/146921379-1e62f4b5-3444-4df8-8134-2a569b020f70.png)

**Comment by blackcrack** [comment]
@kosuodhmwa
Hi Patrick,  
in combination with  
https://github.com/jetspiking/Taskbar11
could it works pretty nice...

best
Blacky
