### ISSUE TITLE
"Replace Start Button" not working properly

### ISSUE THREAD

**Issue by TetterkeT** [Open-Shell/Open-Shell-Menu#911]
I have found a few issues with the Windows 11 start menu button when using Open Shell:

- Unable to access right-click Open Shell context menu unless "Replace Start Button" enabled
- "Replace Start Button" option places the clam shell icon as an overlay on the W11 start button
- Using a blank graphic as the custom start button blanks it out completely

I suppose the simplest fix for this would be to replace the start button with a custom image of the stock W11 Start Button icon, but thus far I have been unable to locate it (in Windows or via Google image search).

**Comment by kraftwerk15** [comment]
I'm just a user of open shell, not a contributor. just wanted to chime in that I just upgraded to W11 this afternoon. open shell ran fine for me after I upgraded and then I shifted the icons on the taskbar back to left alignment.

I tried to recreate the items on this post, but couldn't. everything is working fine for me with a custom image and it appears it is replacing the new W11 icon correctly.

**Comment by JonathanWilcox** [comment]
Perhaps that is the issue then, because my laptop is at 1920 x 1080.

**Comment by shefsam1** [comment]
ditto on the two above (Win 11 upgrade) - in particular clam shell button is offset (to the left) on top of windows start button

**Comment by Dhyfer1** [comment]
Is it that replacing the start menu button is not possible without third party tools? or does anyone have any idea about which dll or exe file the Win11 start menu logo can be found in the taskbar?

**Comment by wol101** [comment]
You can get a very functional version if you use a custom button. The size depends on how you have the screen set up but on my PC a width of 87 pixels is exactly right. I have a 87x261 custom button with the visible button 63x63 and it covers the Windows 11 button perfectly and does not obscure the search icon. You use the 3 button vertical PNG design specified in the manual and I tweaked the colour to match my menu bar.
![Colour-matched background Win11](https://user-images.githubusercontent.com/18628692/149680746-d200409d-8b3d-47b0-bd54-0801e02e7c34.png)
.

**Comment by Dhyfer1** [comment]
@wol101 I want to replace the start menu button in Windows 11, but I don't want to replace the start menu, just the button. Is it possible to do that with Open Shell?

**Comment by wol101** [comment]
@Dhyfer1 I'm sure there are simpler ways but you can set OpenShell so that when you click on it you get the regular Windows menu. That would give you the effect of just changing the start button if that is all you want. Enable "Show All Settings" and the options are under "Controls". But I think at the moment there are issues with the custom button sizes if you change the resolution of your monitor as noted by the original post. Certainly the stock buttons do not fully cover the Windows icon for me (or they cover part of the search icon), and if you can see the Windows icon then you can accidentally click on it.

**Comment by Dhyfer1** [comment]
@wol101 I have never changed the screen resolution of my laptot (1366x768 px) so I think I will have no problem with that. By the way, the 3 images of the Windows logo that you show in your previous message, are the ones you are currently using in Windows 11? That is what I have understood. 

You say: _" The size depends on how you have the screen set up but on my PC a width of 87 pixels is exactly right. I have a 87x261 custom button with the visible button 63x63 and it covers the Windows 11 button perfectly and does not obscure the search icon"_ I would like to know where did you get the width to create the custom button? 87x261?

**Comment by wol101** [comment]
@Dhyfer1 That's right. It's the 3x1 format needed so you get different images for normal, hover and click. I just edited one of the ones I found online because the original had transparent grilles that let you see the underlying orginal button which was ugly. On my screen it is almost perfect but it will depend on the colour choice and I'm running at 150% scale on a 4k screen and I imagine the sizing depends on that too.

<img width="183" alt="Screenshot 2022-01-25 084426" src="https://user-images.githubusercontent.com/18628692/150943540-e09d72e5-c73d-4293-8aba-897e95435552.png">

**Comment by mburr** [comment]
> "Replace Start Button" option places the clam shell icon as an overlay on the W11 start button

Funny!

My two machines were updated to Win11 over the past week or so, and this happened on my laptop but not my desktop.  
I thought it was a feature to allow access to both the OpenShell menu or the Win11 menu.  I spent a bit of time trying to figure out how to get it on my desktop too.  I'm not sure if I like the "feature", but I figured it was worth trying out for a few days to see.

**Comment by ge0rdi** [comment]
Support for Windows 11 start button was added in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).

Unfortunately, it is not possible to _hide_ original start button.
If you want to use custom start button, you need to make sure it covers original button properly.
There should be no fully transparent parts in custom button, because those will cause mouse clicks to go through to original button underneath, So you should always use at least some small amount of alpha.

**Comment by gelavat** [comment]
> You can get a very functional version if you use a custom button.
Thanks a lot for this gif image.
I have redesigned it so that the Windows start menu logos fit at the bottom and not get higher as the task bar, for a 175% scale factor applied (maybe 150% too). It works very nicely for the 3 types of icons displayed properly. It is attached below if it can help others.
![Windows_logo](https://github.com/user-attachments/assets/41284b7e-8247-4f77-903b-16a88c485884)

**Comment by Gipeto55** [comment]
I  joined yesterday github, the problem I have is that when using Win 11 there ids no way to change the Start Button because the windows to specify the file to be used doesn't appera ....
I have another laptop using Windows 10 and it works: on another Win 11 laptop I have I was able some time ago to replce the start button and it keeps the Window 7 like button, no possibility now to change, I tried ... it seems it may be related to a more recent version of Win 11, now I have running Win 11 Home 25H2
Can someone help me or it is posisble a misfubnctionality ?
Massimo from Italy
