### ISSUE TITLE
How can I see the missing MS Edge icon in the Apps Menu in Open-Shell?

### ISSUE THREAD

**Issue by Compumind-2021** [Open-Shell/Open-Shell-Menu#919]
Please see this -

In the default W10 (Metro) Start Menu the entry is correctly listed **with** the MS Edge icon.

In Open-Shell, the icon is just an empty stub placed where the icon should be.

![Open-Shell](https://user-images.githubusercontent.com/95507651/144721968-de03107c-24f6-486a-ad80-98a7112ffa73.png)

Any help appreciated.

Thank you. :)

**Comment by GruNostalgia** [comment]
I too am having this issue. I tried delete the iconcache.db and using winaerotweaker to reset icon cache. nothing fixed it.

**Comment by MarkRH** [comment]
I'm using the Windows 7 Menu Style in Windows 10 Pro and I see the same thing for Microsoft Edge in the Apps list.  Everywhere else shows the Edge Icon fine.  I'm running version 4.4.160.

**Comment by ge0rdi** [comment]
Could you, please, right-click on the Edge item, select `Properties` or `Explore` to see where this item is located?
Also does clicking on that item starts actual Edge?

**Comment by MarkRH** [comment]
In my case I don't get a `Properties` or `Explore` option when right-clicking on it.  It does launch Microsoft Edge though. 

![image](https://user-images.githubusercontent.com/8035962/206911655-16a03b24-79b2-4885-a572-0b6d221a807a.png)

Okay, after clicking on it a couple times I got it to show on the initial menu which did have an `Explore` option which opens to here in the **Applications** folder.

![image](https://user-images.githubusercontent.com/8035962/206911559-7fad0db2-feb0-48dd-8430-66b08f0ee74e.png)

Not quite sure where this extra Microsoft Edge icon is coming from but Open Shell it pointing to it instead of the other Microsoft Edge.

**Comment by ge0rdi** [comment]
I have it the same way on my Win10 machine.

It seems that there is also `Microsoft Edge` store application installed along to _standard_ one.
Not sure how it got to that state, maybe MS was using store application and later they switched to _standard_ non-store one and this is just some leftover that Windows failed to remove.

It is listed in `Applications` folder and we are just enumerating that one to create list of applications.
Also that system folder doesn't contain icon for it so there is not much we can do about it.
We can possibly ignore this entry, but then if somebody has Edge installed from store it won't show for him.
So not sure how to do it safely.

I'd suggest to just try to uninstall the store application (using Powershell? and some googling).
Or just ignore it.

> Open Shell it pointing to it instead of the other Microsoft Edge

Normal `Microsoft Edge` should be listed in `AllPrograms`.

I will close this one as there is not much we can do about.
