### ISSUE TITLE
Win 11 Start menu appears, far side of bottom left screen

### ISSUE THREAD

**Issue by kully51ngh** [Open-Shell/Open-Shell-Menu#983]
The built in windows 11 start menu will still appear, when the mouse is at the very bottom left side of the screen.
Clicking on the open shell button itself, works fine.

**Comment by brisingraerowing** [comment]
That might be the Widgets panel you're seeing. I just turned it off due to the conflict (though the weather info in the taskbar is handy).

**Comment by UncleScrooge85** [comment]
I confirm this issue on Windows 11 with taskbar icons moved to the left side in the options (as everyone using open shell will want to set).
Up to Windows 10, openshell would open up through the standard start button (no need to replace it).
With Windows 11 you need to select a start button replacement icon that will appear over-layered to the standard button. You will still see some pixels of the standard button below the new button, and if you click on these small portions of the standard button, the standard start menu will still show up.
The same happens if you click the bottom-left corner of the screen: the standard start menu shows up, not open shell.

**Comment by kully51ngh** [comment]
Following UncleScrooge85 advice; that seems to work now.
I created a blank white canvas of 68 width by 182 height measured in pixel unit on Photopea, saved it as a PNG file, add that as a custom image, now it works.
Everywhere I click, opens the open shell and not the windows built-in menu.
Thank you for your help.

**Comment by UncleScrooge85** [comment]
Good idea and perfectly working trick.
Developers should integrate it into next release for Windows 11 proper compatibility, so I wouldn't consider this issue actually closed.

**Comment by kully51ngh** [comment]
I'm new to Github, how would I mention this to the devs?
thank you

**Comment by kully51ngh** [comment]
@XenHat @ge0rdi @coddec @Ibuprophen 
Could you get the above mentioned trick integrated to the next release, please?
Thank you

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).
